### ISSUE TITLE
Android: Issues on v0.25.0

### ISSUE THREAD

**Issue by jamesdeperio** [Kotlin/kotlinx.coroutines#511] opened 2018-08-24 07:16 UTC
> **Build Failed.**

* Program type already present: kotlinx.coroutines.experimental.internal.LockFreeMPMCQueueNode
Message{kind=ERROR, text=Program type already present: kotlinx.coroutines.experimental.internal.LockFreeMPMCQueueNode, sources=[Unknown source file], tool name=Optional.of(D8)}

* Program type already present: kotlinx.coroutines.experimental.internal.LockFreeMPSCQueueCore
Message{kind=ERROR, text=Program type already present: kotlinx.coroutines.experimental.internal.LockFreeMPSCQueueCore, sources=[Unknown source file], tool name=Optional.of(D8)}

* Program type already present: kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode
Message{kind=ERROR, text=Program type already present: kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by GeoffreyMetais** [comment] 2018-08-25 09:44
Same here, and with D8 disabled, I get this error:
`Cause: class name (kotlinx/coroutines/experimental/scheduling/LimitingDispatcher) does not match path (META-INF/versions/9/kotlinx/coroutines/experimental/scheduling/LimitingDispatcher.class)`

**Comment by ashdavies** [comment] 2018-08-25 11:49
I had been receiving `unexpectedly contains class` errors with proguard similar to this error

**Comment by elizarov** [comment] 2018-08-25 14:08
I'll close it as a duplicate of #510, since it is all caused by the fact that Android toolchain does not (yet) support multi-version jar file. Let's see whether we can find a good workaround as a part of discussion in #510 and what be a proper way forward.

**Closed by elizarov** 2018-08-25 14:08 UTC
