### ISSUE TITLE
Multi-version jar file problem with Android SDK

### ISSUE THREAD

**Issue by svenjacobs** [Kotlin/kotlinx.coroutines#510] opened 2018-08-24 06:59 UTC
**UPDATE** (from @elizarov): [JEP 238](http://openjdk.java.net/jeps/238) multi-version jars seem to be causing various issue with google toolchain. Reported thus far:

* `MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)`
* `Program type already present: kotlinx.coroutines.experimental.InvokeOnCancellation`, `Program type already present: kotlinx.coroutines.experimental.internal.LockFreeMPMCQueueNode`, etc
* `class name (kotlinx/coroutines/experimental/scheduling/LimitingDispatcher) does not match path (META-INF/versions/9/kotlinx/coroutines/experimental/scheduling/LimitingDispatcher.class)`, etc

**ORIGINAL REPORT**:

Trying to compile an Android project with min SDK 19 and the newly released 0.25.0 I suddenly receive the following build error:

```
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
```

Android Studio: 3.1.4
Android Gradle Plugin: 3.1.4

**Comment by elizarov** [comment] 2018-08-24 07:00
You need to exclude classes that are inside of `META-INF` directory of the jar file. That will be fixed in the upcoming update of the Google toolchain, see https://issuetracker.google.com/issues/77587908

**Comment by elizarov** [comment] 2018-08-25 16:48
Example applications for Android that are included in `kotlinx.corutines` ([example-app](https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android/example-app) and [animation-app](https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android/animation-app) were failing for the same reason (see #512). The following toolchain seems to fix the problem for those applications:
* Gradle version `4.9`
* Android Gradle Tools version to `3.3.0-alpha04`
Please, confirm that it helps with other applications, too.

**Comment by matejdro** [comment] 2018-08-26 10:38
Is there a workaround for this issue without using alpha-stability components?

**Comment by SUPERCILEX** [comment] 2018-08-26 17:57
@elizarov I got [that error](https://github.com/Kotlin/kotlinx.coroutines/issues/517) using AGP `3.3.0-alpha07` and Gradle `4.10`.

**Comment by SUPERCILEX** [comment] 2018-08-26 19:09
@elizarov Nope, it still fails with R8 enabled: `Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: kotlinx.coroutines.experimental.AbstractContinuation`.

**Comment by svenjacobs** [comment] 2018-08-27 05:29
@elizarov Would it be possible to release an artifact of the coroutines library for android without multi-version jar? Like @matejdro said I, too, hesitate to use an alpha version of the build toolchain for my production application.

**Comment by tepex** [comment] 2018-08-28 19:16
In my case it was 0.25.0 coroutines. 0.24.0 -- is OK.

**Comment by igorvilela28** [comment] 2018-08-29 13:44
I'm with this problem too.

Using coroutines 0.25.0,  AGP 3.3.0-alpha05 and gradle 4.9

**Comment by cbruegg** [comment] 2018-08-30 08:17
Indeed the complete switch to multi-version JARs seems a bit premature. Especially when multiple developers are working on a project, it's not easy to switch to alpha-level build components.

**Comment by Mracobes9** [comment] 2018-08-30 08:37
So someone know how to fix  it ?

**Comment by ezamelczyk** [comment] 2018-08-30 14:02
@Mracobes9 revert to 0.24.0

**Comment by Mracobes9** [comment] 2018-08-30 14:10
@ezamelczyk . revert what ? Coroutines ?

**Closed** 2018-09-04 13:47 UTC
Labels: bug

**Comment by elizarov** [comment] 2018-09-04 18:00
Use `kotlinx.coroutines` version `0.25.3`.
