### ISSUE TITLE
withTimeout never thrown TimeoutCancellationException

### ISSUE THREAD

**Issue by francismariano** [Kotlin/kotlinx.coroutines#2394] opened 2020-11-16 20:00 UTC
Hello guys,

Here is a basic test with timeout in an Android app. In this case, println never is called because TimeoutCancellationException is not thrown, in normal behavior the app should to crash, but it is not.

```
fun testeTimeout() {
    mainScope.launch {
        val ret = getTimeoutInt()
        println(ret)
    }
}

suspend fun getTimeoutInt() : Int {
    return withTimeout(1000) {
        delay(5000)
        10
    }
}
```

However, if the getTimeoutInt is enclosed with try/catch the exception is thrown normally. 

```
fun testeTimeout() {
    mainScope.launch {
        try {
            val ret = getTimeoutInt()
            println(ret)
        } catch (e: Exception) {
            println("ret = $e)
        }
    }
}
```

ret = kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms

**Is it a bug that?** 
Kotlin : 1.4.20-RC
Coroutine: kotlinx-coroutines-android:1.4.1

Thank you

**Comment by qwwdfsad** [comment] 2020-11-17 10:58
`TimeoutCancellationException` is successfully thrown from `delay` method (you can see it by wrapping it into `try-finally` or `try-catch`) and coroutine from `testeTimeout` is terminated. It's just not printed to the console

**Comment by francismariano** [comment] 2020-11-17 11:10
I see the exception when I wrapping it with `try-catch`. 

But I think that the application should be crashed if the `TimeoutCancellationException` is successfully thrown and it is not catch with `try-catch`.

**Comment by qwwdfsad** [comment] 2020-11-17 13:16
I see, this is because `TimeoutCancellationException` is `CancellationException` and `CancellationException` can neither crash an application nor get reported.
Let me close it as a duplicate of #1374

**Closed by qwwdfsad** 2020-11-17 13:16 UTC
Labels: question
