### ISSUE TITLE
Workround #3881 breaks non-local returns in 1.8.0-RC

### ISSUE THREAD

**Issue by Amejonah1200** [Kotlin/kotlinx.coroutines#3985] opened 2023-12-12 20:47 UTC
I recently upgraded the lib of one of my apps from `1.7.3` to `1.8.0-RC`. I saw that something wasn't working a day later in my Grafana. After some investigations and deductions, I figured out that this bump caused functions not being executed, something had to do with locks.

After some time, I very professionally (using lots of `println`s) debugged the whole code related to that feature. I found the bug out:

```kt
fun test() {
  mutex.withLock {
    return
  }
}
```

This doesn't release the lock. Why? Because someone decided to remove `finally` of that damn thing in #3881 .

![image](https://github.com/Kotlin/kotlinx.coroutines/assets/50181314/95fbfaaa-22fe-4221-a419-4412e6c1cbad)
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/50181314/784a8f60-e328-4903-a4ae-f01674e8b6e2)
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/50181314/46fb835f-b7b8-48a1-acfa-6996dd784c18)

https://kotlinlang.org/docs/inline-functions.html this even shows how to make a lock function which works. This will break a lot of code which relies on of having a finally out there.

**Comment by CLOVIS-AI** [comment] 2023-12-12 21:34
Ouch, that's a pretty big oversight. I'll let the team chime in on this one, I have no idea how to fix this without bringing back the original bug.

**Comment by jakobkmar** [comment] 2023-12-12 22:07
> I have no idea how to fix this without bringing back the original bug.

Isn't the original compiler bug ([KT-58685](https://youtrack.jetbrains.com/issue/KT-58685)) fixed in Kotlin 1.9.30 (or at least 2.0.0)? I guess the workaround can be removed then?

**Comment by dkhalanskyjb** [comment] 2023-12-13 09:47
Thank you for your immense professionalism! `println` FTW.

Also, thank you for making the RC process work as intended. Breakage is expected in RC, and the saddest thing is when we publish an RC, no one finds an issue, but after the release, all the production code is suddenly broken.

**Comment by werner77** [comment] 2023-12-21 10:09
Could this be fixed with:

```
val result = try {
   action().also { unlock(owner) }
   ...
```

**Closed** 2023-12-21 15:36 UTC
Labels: bug
