### ISSUE TITLE
Unresolved reference for kotlinx.coroutines on iOS

### ISSUE THREAD

**Issue by tethridge** [Kotlin/kotlinx.coroutines#4056] opened 2024-02-29 19:56 UTC
**Describe the bug**
Upgrading from 1.7.3 to 1.8.0 causes imports under iosMain in a multiplatform project to show a "unresolved reference" error for kotlinx.coroutines.

What happened? What should have happened instead?
Upgrading to 1.8.0 should not cause kotlinx.coroutines to be unresolved.

How to reproduce:
- Create a new multi-platform project that includes iOS.
- Add a dependency on "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
- Add a reference to Dispatchers.Default in one of the Kotlin files under iosMain
- The import will resolve as expected.
- Update the version to 1.8.0 and sync gradle
- Android Studio will not report that kotlinx.coroutines cannot be resolved.

**Comment by dkhalanskyjb** [comment] 2024-03-01 07:23
I followed your instructions exactly, but the issue didn't reproduce: `Dispatchers.Default` is resolved properly. Please ensure that the Kotlin version is at least 1.9.0 (but preferably, 1.9.21), and also try to build the project. If compilation doesn't report any errors, this means that the problem is on the side of Android Studio. If your project doesn't build with 1.8.0 but builds with 1.7.3, please provide a reproducer.

**Comment by dkhalanskyjb** [comment] 2024-03-08 09:41
@cunhap, please read my message above.

**Comment by cunhap** [comment] 2024-03-08 10:53
I have. I am using the latest IntellJ Ultimate, not Android Studio. It also happens when I add the `js` target. I think it's an IDE issue here as well, the code is compiling fine using the gradle assemble task. Any suggestions? It's harder to code without the IDE accessing the information properly.

**Comment by dkhalanskyjb** [comment] 2024-03-08 11:03
> code is compiling fine using the gradle assemble task

That's the critical part. This means that our library provides all the information needed for the compiler (and therefore, ideally, the IDE).

This should be filed to https://youtrack.jetbrains.com/newIssue?project=KTIJ. Please include the build number of the IDE and which configs you have set in `Settings → Languages & Frameworks → Kotlin`.

**Comment by dkhalanskyjb** [comment] 2024-03-12 12:10
Closing the issue for now, as it seems like it's not related to the coroutines library. If we receive some new information about the problem, we'll reopen the issue.

**Closed by dkhalanskyjb** 2024-03-12 12:10 UTC
Labels: waiting for clarification
