### ISSUE TITLE
Channels, Jobs, etc. should allow listeners to be set for reactive handling

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#222] opened 2018-02-06 04:07 UTC
It would be nice if I could configure a `Channel` or `Job` to reactively handle an event, like `onCancel`. Perhaps a listener should be allowed for this, or even a suspending method to allow for some reactive handling of cancelation events. Not being able to detect this event and handle it properly in some cases limits my ability to use this library to proactively clean things up.

**Comment by elizarov** [comment] 2018-02-06 07:44
There is a way to install those handlers on jobs with `invokeOnCompletion`. It is named in such a long and baroque way by design to discourage the use of this method as much as possible. `Channel` does not yet have any method like that (even though there is some demand) simply because I have not figured out a natural way to implement it yet. There are some thoughts on tighter integration between `Job` and `Channel` (`channel.job` property anyone?) which might address this demand.

Anyway, with coroutines the recommended pattern to handling events it totally different from Rx way of doing things. Why? When you install an Rx-like handler it is never totally clear in what thread/context it is going to be executed and whether this invocation is synchronous or asynchronous. 

So, with coroutines if you have `val job: Job = ...` and you want to execute some code when it completes you write:

```
launch { // you can also explicitly specify context 
    job.join()
    doSomethingWhenJobCompletes() // it can easily be a suspending function
}
```

You can write an extension function that captures the above pattern and try using it in your projects. See if that helps.

**Comment by ScottPierce** [comment] 2018-02-06 15:15
What about `onCancel`?

**Comment by elizarov** [comment] 2018-02-06 17:56
Normally, the following code shall be used as `onCancel`:
```
launch { 
    job.join()
    if (job.isCancelled) { ... }
```
in this case the code gets executed after the completion of the `job`. 

If you want _synchronous_ notification as soon as `job.cancel` is invoked, then you shall use `job.invokeOnCompletion(onCancelling= true) { ... }`. However, one shall be extremely careful with the later approach due to its synchronous nature. It is actually used internally to cancel all the children when parent is cancelled.

**Comment by odahcam** [comment] 2020-02-21 15:41
What about  `channel`s?

Considering I wanna do something immediately after the channel is closed:

```Kotlin
val channel = ConflatedBroadcastChannel()
val broadcastReceiver = { /* receives values and offers in the channel */ }

channel.invokeOnClose { closeReceiver(broadcastReceiver, context) }

// ...

if (shouldComplete) channel.close()
```

Can we rely on `invokeOnClose` for any kind of "stream end" events like this scenario?

**Comment by elizarov** [comment] 2020-03-13 14:10
@odahcam Yes. `invokeOnClose` is reliable, how I'd strongly suggest finding another way to write the code like that. Let us take a specific use-case. Why would you want to do something after the channel is closed? Where is the code that sends to that channel?

**Comment by odahcam** [comment] 2020-03-17 00:17
I would like to return the `ReceiverChannel` from my method and perform certain action when the user closes it. Just like that. That receive channel is from a scanner proccess and the scan should be stopped if the channel is closed.

**Comment by elizarov** [comment] 2020-03-17 07:18
You should use `try/finally` in this case. The remmended way to do it is like this:

```
fun CoroutineScope.doSomeActions(): ReceiveChannel<DataType> = produce {
    try {
          // actually run the scanner
    } finally { 
         // execute code when caller cancels the channel
   }
}
```

Does it help? 

P.S. `ReceiveChannel` cannot be closed by a user, the correct term here is `cancel`.

**Comment by odahcam** [comment] 2020-03-17 16:10
In fact not so much to be entirely truth, I did not understand how it works.

**Comment by elizarov** [comment] 2020-03-17 17:18
@odahcam What do you mean? Do you still have the issue of listening to channel closing?

**Comment by odahcam** [comment] 2020-03-19 23:55
Nope, I can listen to that w/o any problem, I just did not understood your explanation.

**Comment by elizarov** [comment] 2020-03-20 10:20
I'm closing it. It does not seem that we have any use-cases that would warrant additional special APIs for close listeners.

**Closed by elizarov** 2020-03-20 10:20 UTC
Labels: enhancement
