### ISSUE TITLE
Double locking Mutex?

### ISSUE THREAD

**Issue by Mygod** [Kotlin/kotlinx.coroutines#965] opened 2019-02-01 18:12 UTC
```
val lock = Mutex()
lock.withLock {
    lock.withLock { }
}
```

This causes a deadlock. This code would be useful if, imagine the second block is in another method that can be reused.

**Comment by SeekDaSky** [comment] 2019-02-02 11:00
It's not a bug, it is its intended purpose, a mutex can not be locked twice without being unlocked first.

**Comment by qwwdfsad** [comment] 2019-02-04 08:51
It is written in the documentation: 
>It is **non-reentrant**, that is invoking [lock] even from the same thread/coroutine that currently holds the lock still suspends the invoker.

It is hard to implement in a reentrant manner without additional token because there is no identity in coroutines. E.g. how would you implement a function with the following signature: `suspend fun holdsLock(): Boolean`?

As a workaround, you can assign token to each coroutine manually and use it with `lock(owner)` and `holdLock(owner)`

**Closed by qwwdfsad** 2019-02-04 08:51 UTC
Labels: question

**Comment by Mygod** [comment] 2019-02-04 09:00
Why is that a problem? I think there is already an equivalence of thread-local in Kotlin coroutine world?

**Comment by fvasco** [comment] 2019-02-04 09:06
> I think there is already an equivalence of thread-local in Kotlin coroutine world?

This is a statement or a question?

**Comment by qwwdfsad** [comment] 2019-02-04 09:11
> I think there is already an equivalence of thread-local in Kotlin coroutine world?

There is, but it is intrusive and you should always specify it when launching a coroutine.
This is fine for the integration with a blocking world, but not for the integration with a `Mutex` in the same package. This is just way too error-prone

**Comment by Mygod** [comment] 2019-02-04 09:12
Oh I just mean that I think it's not hard to implement the reentrant lock
with thread locals.

**Comment by Mygod** [comment] 2019-02-07 07:18
Could it do something like wrap the block with a new context with that thread-local defined?

**Comment by qwwdfsad** [comment] 2019-02-07 08:28
Probably yes, but there will be other issues with multiple coroutines on the same thread and disability to mutate thread-local-as-context-element
