### ISSUE TITLE
A few ANRs happening on Android 13 (Samsung only)

### ISSUE THREAD

**Issue by paolop** [Kotlin/kotlinx.coroutines#3940] opened 2023-11-13 15:44 UTC
**Describe the bug**

jdk.internal.misc.Unsafe.putReferenceVolatile: ANR triggered by slow operations in main thread

```
main (runnable):tid=1 systid=17267 
#00 pc 0x438384 libart.so (art::DumpNativeStack + 108) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
#01 pc 0x474f5c libart.so (art::Thread::DumpStack const + 828) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
#02 pc 0x474624 libart.so (art::DumpCheckpoint::Run + 208) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
#03 pc 0x2f69dc libart.so (art::Thread::RunCheckpointFunction + 140) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
#04 pc 0x57f178 libart.so (artTestSuspendFromCode + 204) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
#05 pc 0x376a1c libart.so (art_quick_test_suspend + 156) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
       at jdk.internal.misc.Unsafe.putReferenceVolatile(Native method)
       at jdk.internal.misc.Unsafe.putReferenceRelease(Unsafe.java:2459)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.lazySet(AtomicReferenceFieldUpdater.java:474)
       at kotlinx.coroutines.internal.LockFreeLinkedListNode.tryCondAddNext(LockFreeLinkedList.kt:226)
       at kotlinx.coroutines.internal.LockFreeLinkedListNode.addLastIfPrevAndIf(LockFreeLinkedListNode.java:181)
       at kotlinx.coroutines.channels.AbstractSendChannel.enqueueSend(AbstractChannel.kt:1166)
       at kotlinx.coroutines.channels.ArrayChannel.enqueueSend(ArrayChannel.kt:130)
       at kotlinx.coroutines.channels.AbstractSendChannel.sendSuspend(AbstractChannel.kt:196)
       at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:136)
       at logger.domain.loggers.database.DatabaseLogMessageMediatorKt$produce$1.invokeSuspend(DatabaseLogMessageMediator.kt:97)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith(DispatchedContinuation.java:256)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:1)
```

**Provide a Reproducer**
It is not possible to provide a toy app to get a repro. We just had two repros reported in Crashlytics.

The following code is the one that is triggering the ANR:

```
private fun CoroutineScope.produce(
        logMessage: LogMessage,
        channel: SendChannel<LogMessage>
) = launch {
    channel.send(logMessage)
}
```
Where the CoroutineScope is defined as follows:

`CoroutineScope(Dispatchers.Unconfined + SupervisorJob())`

and the channel is:
`Channel(CHANNEL_BUFFER_CAPACITY)`

**Library version**
1.6.2

I'm aware that the library version is outdated, but I just want to understand if a library update is enough to get this issue sorted out or if it is something still relevant.

***
I already checked out previous opened issues about ANRs like: 
- https://github.com/Kotlin/kotlinx.coroutines/issues/3429
- https://github.com/Kotlin/kotlinx.coroutines/issues/1038

But I cannot see a correlation between them and this one

**Comment by dkhalanskyjb** [comment] 2023-11-14 12:57
It's tough to say what causes this without a reproducer, but a library version upgrade *may* be helpful in this case: since 1.7.0, a new, more performant implementation is used for channels, which may solve your problem. So, please try updating to the new version. I'll close the issue in the meantime, but feel free to `@`-mention me if the issue persists after an upgrade / if someone else encounters this, and we'll reopen this.

**Closed by dkhalanskyjb** 2023-11-14 12:57 UTC
Labels: bug
