### ISSUE TITLE
 TextMeasurer.measure only works in Dispatchers.Main on ios

### ISSUE THREAD

**Issue by Mohamed-Mabrouki** [Kotlin/kotlinx.coroutines#4168] opened 2024-07-08 09:20 UTC
i have a text measurement that is pretty heavy so Dispatchers.Main will cause lag but when i change the context to another dispatcher it works fine on android but it crashes on ios.

` textLayoutResult =
                                textMeasurer.measure(
                                    text = simpleAnnotatedString,
                                    style =
                                        defaultStyle.copy(
                                            fontSize = fontSize.sp,
                                            fontWeight = FontWeight(uiState.fontWeight),
                                        ),
                                    constraints =
                                        Constraints.fixed(
                                            width = lineWidth,
                                            height = lineHeight,
                                        ),
                                    maxLines = 1,
                                    softWrap = false,
                                    overflow = TextOverflow.Visible,
)`

**Comment by dkhalanskyjb** [comment] 2024-07-09 09:36
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/5073. Also, this isn't even the right issue tracker: this is for the coroutines library.

**Closed by dkhalanskyjb** 2024-07-09 09:36 UTC
Labels: bug
