### ISSUE TITLE
App crashing from apk install

### ISSUE THREAD

**Issue by priyaljain-tiket** [Kotlin/kotlinx.coroutines#1025] opened 2019-03-04 05:44 UTC
After changing to coroutines version to 1.0.1, our android apk is causing the app to crash on AWS device farm handsets.App works fine on local devices.

**Comment by qwwdfsad** [comment] 2019-03-04 07:59
This is likely to be duplicate of #849, please keep track there

**Closed by qwwdfsad** 2019-03-04 07:59 UTC
