### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException

### ISSUE THREAD

**Issue by michal-chojnacki** [Kotlin/kotlinx.coroutines#1032] opened 2019-03-08 11:01 UTC
One of the devices I have a lot of crashes like that:

```
Fatal Exception: java.lang.ClassCastException
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.targetCheck(AtomicReferenceFieldUpdater.java:244)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.get(AtomicReferenceFieldUpdater.java:293)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.getAndSet(AtomicReferenceFieldUpdater.java:151)
       at kotlinx.coroutines.scheduling.WorkQueue.poll(WorkQueue.kt:65)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.findTaskWithCpuPermit(CoroutineScheduler.kt:969)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.findTask$kotlinx_coroutines_core(CoroutineScheduler.kt:944)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:725)
```

What can be the reason and how can I avoid such situations?
Device Rockchip RK3368-Box
Android 6.0.1
Kotlin version 1.3.21
Coroutines version 1.1.1

**Comment by qwwdfsad** [comment] 2019-03-12 08:41
It is #490

Sadly, we have no workaround for this problem and we can't reproduce it locally :(

**Comment by qwwdfsad** [comment] 2019-03-12 08:45
It is very suspicious. It looks like #490, but it is not.
Can you reproduce this problem locally or using an emulator?

**Comment by michal-chojnacki** [comment] 2019-03-14 12:21
I wasn't able to reproduce it. However problem disappeared. I found at the code that Job wasn't canceled for one ViewModel during onCleared. Maybe this was the reason of this issue.

**Comment by qwwdfsad** [comment] 2019-03-14 12:27
Ok, then I am closing this issue.
Feel free to reopen it if you will have this issue again

**Closed by qwwdfsad** 2019-03-14 12:27 UTC
Labels: waiting for clarification

**Comment by xudshen** [comment] 2019-04-01 08:28
I got the same problem here, but I haven't reproduced it yet.

```
Fatal Exception: java.lang.ClassCastException
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.throwAccessCheckException(AtomicReferenceFieldUpdater.java:388)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.accessCheck(AtomicReferenceFieldUpdater.java:379)
       at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.getAndSet(AtomicReferenceFieldUpdater.java:442)
       at kotlinx.coroutines.c.o.b(WorkQueue.kt:65)
       at kotlinx.coroutines.c.a$b.p(CoroutineScheduler.kt:950)
       at kotlinx.coroutines.c.a$b.k(CoroutineScheduler.kt:928)
```

And this crash happens all among the devices.
<img width="753" alt="Screen Shot 2019-04-01 at 16 24 24" src="https://user-images.githubusercontent.com/3141344/55313623-d367c200-549a-11e9-8734-b61eac8f2f5d.png">

Kotlin version 1.3.0
Coroutines version 1.0.0
