### ISSUE TITLE
cannot use kotlinx-coroutines-bom in ver 1.6.3 since it always tries to download a jar

### ISSUE THREAD

**Issue by vivekmalhotragithub** [Kotlin/kotlinx.coroutines#3338] opened 2022-06-22 12:13 UTC
Have this in my project pom.xml
```        
           <dependency>
                <groupId>org.jetbrains.kotlinx</groupId>
                <artifactId>kotlinx-coroutines-bom</artifactId>
                <version>${kotlin.coroutines.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
but it tries to download kotlinx-coroutines-bom:1.6.3:jar which does not exist.

**Comment by JakeWharton** [comment] 2022-06-22 13:24
Probably a dupe of/same as #3334.

**Comment by qwwdfsad** [comment] 2022-06-22 19:47
Yep, duplicate of #3334

**Closed by qwwdfsad** 2022-06-22 19:47 UTC
