### ISSUE TITLE
Can't install app after upgrade from 1.2.0-alpha-2 to 1.2.0

### ISSUE THREAD

**Issue by b95505017** [Kotlin/kotlinx.coroutines#1108] opened 2019-04-17 10:06 UTC
It always shows `INSTALL_FAILED_DEXOPT` after upgrade to 1.2.0. Is there any clue to cause this issue?

**Comment by qwwdfsad** [comment] 2019-04-17 10:20
Please provide a proper self-contained reproducer of your problem with a detailed explanation of what is wrong.

**Comment by b95505017** [comment] 2019-04-22 09:26
I use [this example](https://github.com/googlecodelabs/kotlin-coroutines.git) and change kotlin dependencie to `1.3.0` and coroutines to `1.2.0` then install (`./gradlew :app:installDebug`) to `HTC_E9pw - 5.0.2` will meet `INSTALL_FAILED_DEXOPT` while using `1.2.0-alpha-2` works OK.

**Comment by wilfordw** [comment] 2019-08-13 06:26
I get the same problem. `1.2.1` shows INSTALL_FAILED_DEXOPT when `1.1.1` work fine

**Comment by LouisCAD** [comment] 2019-08-13 07:25
Which Android Gradle Plugin version are you using, and did you explicitly disable or enable R8?

**Comment by hjywyj** [comment] 2019-10-26 01:41
同样的问题，解决了吗

**Comment by hjywyj** [comment] 2019-10-26 07:32
https://github.com/Kotlin/kotlinx.coroutines/issues/1635

**Comment by Tolriq** [comment] 2019-10-26 07:33
This is probably https://issuetracker.google.com/issues/126056766 comment there :)

**Comment by enbandari** [comment] 2019-12-03 00:18
any workaround？

**Comment by Tolriq** [comment] 2019-12-03 07:30
Star and comment so that they answer :) This is strange R8 team is one of the best usually, so they probably just don't care at all as it's a very very very small user fraction.

**Comment by qwwdfsad** [comment] 2019-12-13 13:22
Closing as Android toolchain-specific issue.
Feel free to create a new one if you think the problem is library-specific and please attach a reproducer

**Closed by qwwdfsad** 2019-12-13 13:22 UTC
Labels: android, waiting for clarification
