### ISSUE TITLE
Flow.collect still receive value after invoke CoroutineContext.cancel

### ISSUE THREAD

**Issue by baoti** [Kotlin/kotlinx.coroutines#1753] opened 2020-01-07 10:00 UTC
```kotlin
viewLifecycleOwner.lifecycleScope.launchWhenCreated {
    flow {
        while (true) {
            delay(Random.nextLong(50) + 10)
            emit("launchWhenCreated - ${SystemClock.uptimeMillis()}")
        }
    }
        .flowOn(Dispatchers.Default)
        .collect {
            val currentState = viewLifecycleOwnerLiveData.value?.lifecycle?.currentState
            Timber.d("collect: $value - $currentState")
            if (currentState.isAtLeast(Lifecycle.State.CREATED) != true) {
                // this.isActive == false
                Timber.w("Oops! collect: $value - $currentState")
            }
        }
}
```

In `LifecycleCoroutineScopeImpl.onStateChanged(ON_DESTROY)`, called `coroutineContext.cancel()`, but `collect` still receive value on next loop.

**Comment by ThanosFisherman** [comment] 2020-01-10 11:25
I encountered the same problem here

https://stackoverflow.com/questions/59680533/how-to-cancel-unsubscribe-from-coroutines-flow

Is there any workaround for that? Am I missing something?

**Comment by elizarov** [comment] 2020-03-25 14:56
This is a duplicate of #1265

**Closed by elizarov** 2020-03-25 14:56 UTC
Labels: flow
