### ISSUE TITLE
Creating DAGs with channels - proposing transforms and pipes

### ISSUE THREAD

**Issue by venkatperi** [Kotlin/kotlinx.coroutines#312] opened 2018-04-07 14:19 UTC
## Directed Graphs 
Think directed graphs of channels & coroutines with `producers` as message sources and `actors` as sinks. What's missing in this picture is:
- intermediate transform nodes 
- graph edges / interconnects or piping

e.g. NodeJS [Streams](https://nodejs.org/api/stream.html#stream_stream) uses similar concepts for high throughput and performance. 

## The Proposal
I'm proposing adding a couple of coroutines (note that these are early prototypes and not up to par with producer et al):
- [transform coroutine](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/coroutine/Transform.kt) - like `produce` & `actor`, a `transform` is a combination of a coroutine, the state that is confined and is encapsulated into this coroutine, and two channels to communicate with upstream and downstream coroutines.
- [pipe coroutine](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/coroutine/Pipe.kt) - a stateless coroutine that consumes messages from a `ReceiveChannel` and send them to a downstream `SendChannel`. When the downstream `SendChannel` is part of a `Channel`, it returns the downstream channel's `ReceiveChannel` for further chaining (like a shell pipe sequence `$ cmd1 | cmd2 | cmd3 ...`).

![dag](https://user-images.githubusercontent.com/1389947/38503988-877dbc3c-3be1-11e8-81d2-188a8667704b.png)

### Example 1
This example reads blocks (default 1024) as `ByteBuffer`s from a file and decodes the blocks to `utf8`. 
```kotlin
val data : String //the file's contents

FS.createReader(inputFile.toPath())
 .pipe(decodeUtf8())
 .pipe(contents {
   assertEquals(data, it.joinToString { "" })
 })
 .drainAndJoin()
```
* [`createReader`](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/util/FS.kt#L20) returns a ReceiveChannel wrapper around `aRead`
* [`decodeUtf8`](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/util/Utils.kt#L76) receives `ByteBuffer`s and returns `String`
* [`contents`](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/util/Utils.kt#L46) is a transform which returns a list of all messages after the channel closes

### Example 2
Like the previous example, here we read blocks, convert them to utf8 strings and further split text into lines and count the number of lines.

```kotlin
val data : String //the file's contents
val lines = data.split("\n")

val listener = Channel<String>()
val count = async(coroutineContext) {
  listener.count()
}
val teeListener = tee(listener, context = coroutineContext)

FS.createReader(inputFile.toPath())
  .pipe(decodeUtf8())
  .pipe(splitter)
  .pipe(teeListener)
  .pipe(contents {
    assertEquals(lines.size, it.size)
  })
  .drainAndJoin()

assertEquals(lines.size, count.await())
```

* [`splitLine`](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/util/Utils.kt#L86) splits incoming `String` blocks into individual lines and pushes each line as a message on its downstream channel.
* [`tee`](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/util/Utils.kt#L26) is a passthrough transform that replicates messages on the provided `ReceiveChannel`

## Current Alternatives
As @jcornaz points out in the discussion below, transforms (with state) can be implemented as extensions of `ReceiveChannel`. The snippets (from this [test](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/test/kotlin/com/vperi/kotlinx/coroutines/experimental/PipeExamples.kt)) below contrast the two approaches (extensions are cleaner):
### With Transforms/Pipes
```kotlin
 dataProducer()                 // emit chunks of 512 bites
  .pipe(tee(verifyLength))      // verify that we're getting all of the data
  .pipe(splitter(NL))           // split into lines
  .pipe(counter(lineCounter))   // count lines
  .pipe(splitter(WS, true))     // split lines into words (words are aligned)
  .pipe(counter(wordCounter))   // count words
  .drainAndJoin()               // wait
```

### With Extensions
```kotlin
dataProducer()                  // emit chunks of 512 bites
  .tee(verifyLength)            // verify that we're getting all of the data
  .split(NL)                    // split into lines
  .countMessages(lineCounter)   // count lines
  .split(WS, true)              // split lines into words (words are aligned)
  .countMessages(wordCounter)   // count words
  .drain()                      // wait
```

## Question
Question: is this something the team considers worth pursuing?

**Comment by gildor** [comment] 2018-04-09 02:39
It's not clear to me how this new API better than standard map/flatMap. If you want to do it lazy, just wrap to lambda.
Could you show some working, self-contained example? I would like to try to rewrite it using existing channel operators and compare result

**Comment by venkatperi** [comment] 2018-04-09 13:00
* Like `produce` and `actor`, `transform` gives you the ability to add context unlike map/flatMap. 
* Not sure if map et al can use suspending methods, whereas like `produce`, `transform` requires a call to `output.send` so you can suspend within the transform.
* Re. `pipe`, its basically a `consume` loop, but I imagine a coroutine is needed to host that loop. 

I added a (somewhat standalone) [test]( https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/test/kotlin/com/vperi/kotlinx/coroutines/experimental/PipeExamples.kt) to the repo (clone and build with gradle). Let me know if works for doing a comparison:

**Comment by venkatperi** [comment] 2018-04-09 13:27
By `context`, I meant state (additional variables). e.g. in the actor [example](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#actors), `var counter` is tracked outside the channel.

**Comment by venkatperi** [comment] 2018-04-09 13:34
In addition to `consumeEach`, pipe returns `ReceiveChannel` (where appropriate) for chaining, like a shell pipe chain: ` $ a | b | c | d`.

**Comment by venkatperi** [comment] 2018-04-09 14:08
There's a matter of best-approach w.r.t. chaining: adding extensions to `ReceiveChannel` vs providing a reference to a `pipe` like function. 

e.g. `sendTo` seems like a good extension to add, and even include in the stdlib, but should every "chainable transform" be written as an extension? Extensions definitely look cleaner...

**Comment by jcornaz** [comment] 2018-04-09 15:06
>should every "chainable transformation" be written as an extension? Extensions definitely look cleaner

In my opinon: yes. It leads to code easier to read and understand. 

And if transform should are written as extension function, then `produce` allows us to have any necessary mutable state.

Example:
```kotlin 
fun <E> ReceiveChannel<E>.myStatefulOperator(): ReceiveChanne<Int> = produce {
   var count = 0
   consumeEach { send(count++) }
}

**Comment by venkatperi** [comment] 2018-04-09 15:25
I (added)[https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/src/test/kotlin/com/vperi/kotlinx/coroutines/experimental/PipeExamples.kt#L85] an alternative using extensions (w/produce) vs transform.

**Comment by venkatperi** [comment] 2018-04-10 03:46
Simiarl to #257

**Comment by SolomonSun2010** [comment] 2018-05-03 08:30
see also: KT-24223 Feature request: add the pipelines operators in Kotlin
https://youtrack.jetbrains.com/issue/KT-24223

**Comment by SolomonSun2010** [comment] 2018-08-20 02:28
Data-Driven Concurrency is cool !
see also: https://dl.acm.org/citation.cfm?doid=3154814.3162014

Building Scalable, Highly Concurrent & Fault Tolerant Systems - Lessons Learned
https://www.slideshare.net/jboner/building-scalable-highly-concurrent-fault-tolerant-systems-lessons-learned?from_action=save

Dataflow Concurrency
• Deterministic
• Declarative
• Data-driven
• Threads are suspended until data is available
•  Lazy & On-demand
• No difference between:
•  Concurrent code
•  Sequential code
• Examples: Akka & GPars

**Comment by qwwdfsad** [comment] 2019-02-27 14:41
This is kind-of duplicate of #254, so closing this as outdated

**Closed by qwwdfsad** 2019-02-27 14:41 UTC
Labels: enhancement
