### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'context' of undefined" when compiling to JS

### ISSUE THREAD

**Issue by structuresend** [Kotlin/kotlinx.coroutines#1145] opened 2019-04-25 23:12 UTC
seems similar to this, but the link is dead: https://github.com/Kotlin/kotlinx.coroutines/issues/352

```
import kotlinx.coroutines.*

val pass=Unit

class Brainbot(program:String){ 
    private var prog=bbcompiler.Brainbot2BBCL(program)
    var BBCL=prog.show_data()
    private var running=false
    private var coderun : Deferred<Int>? = null

    suspend fun run(input:Int):Int? = coroutineScope{
        var x:Int?=null
        if(running)
            throw Exception("already running")
        running=true
        coderun=async{runProgram(prog, input).result}
        coderun?.await()
    }

    suspend fun run(input:Int?):Int?
    {
        if(input==null)
            return run(0)
        return run(input)
    }

    fun halt()
    {
        if(!running)
            throw Exception("Not running!")
        coderun?.cancel()
        running=false
    }
}
```

Error:

```
libs.js:166 Uncaught TypeError: Cannot read property 'context' of undefined
    at Coroutine$run.Jb (libs.js:166)
    at new Coroutine$run (brainbot.js:1526)
    at Object.run (brainbot.js:1587)
    at HTMLButtonElement.onclick (index.html:19)
```

I might be doing something wrong or this might be a bug

Is there any workaround for this

**Comment by elizarov** [comment] 2019-04-26 07:21
What version of Kotlin Compiler and library are you using?

**Comment by structuresend** [comment] 2019-04-27 00:19
Kotlin 1.3.30, Coroutines 1.2.0

btw I ended up solving this by using Javascript Workers instead, for anyone reaching here from Google

**Comment by elizarov** [comment] 2019-04-27 14:00
Do you have a self-contained example with problem to file a bug for JS compiler? It does not seem to be related to #325, though, since thing code does not seem to have any suspend properties or do you use them somewhere else?

**Comment by qwwdfsad** [comment] 2019-06-28 15:57
Closing as outdated

**Closed by qwwdfsad** 2019-06-28 15:57 UTC
Labels: waiting for clarification

**Comment by rainerkern** [comment] 2019-07-06 19:22
I hope this helps some googler since this ticket is the top result for the error message
I found a very ugly workaround which works (for my purposes)

Using Kotlin 1.3.41 and Coroutines 1.3.20M2

An example Kotlin function:
```kotlin
suspend fun doStuff(/*note! no function arguments here*/) {
    println("printed from the Frontend Kotlin File")
}
```

will get compiled to this
```js
function doStuff(continuation_0, suspended) { 
    var instance = new Coroutine$main(continuation_0);
    if (suspended)
      return instance;
    else
      return instance.doResume(null);
  }
```
The first parameter of a suspend function in Javascript is apparently a coroutine continuation,
Afaik this is just a proxy function handling the coroutine logic - since the actual logic will reside in another (anonymous) function

While debugging you can see that the `continuation_0` is undefined in java, so passing Kotlin's `EmptyContinuation` to the function works (at least in some cases)

```javascript
myapp.doStuff(kotlin.kotlin.coroutines.js.internal.EmptyContinuation);
```

Cheers and all the best,
Rainer

**Comment by rainerkern** [comment] 2019-07-06 20:55
Actually, there is a much much better way

Wrap your Kotlin function in a javascript promise
```kotlin
fun doStuff(): Promise<String> = //or Promise<Unit> for voids
    GlobalScope.promise { 
        callToActualSuspendFunction() // return a String
    }
```
```javascript
output.doStuff().then(function(returnValue) {
    alert (returnValue);
});
```

**Comment by qwwdfsad** [comment] 2019-07-15 16:35
>I hope this helps some googler since this ticket is the top result for the error message

How did you get this error message? By trying to invoke suspend function from javascript and passing `null` to the last parameter?

**Comment by rainerkern** [comment] 2019-07-16 08:10
Hi @qwwdfsad,

> How did you get this error message? By trying to invoke suspend function from javascript and passing null to the last parameter?

Well, probably yes (my JS-Fu is not at 100% ;-)).
I called `doStuff()` as it was defined in Kotlin - so without any parameters. Thus, since the JS Version has parameters, they would all be null
cheers

**Comment by boyvanduuren** [comment] 2019-07-16 19:07
I reproduced the issue in https://github.com/boyvanduuren/reproducer. The kotlin is already compiled to JS in there, but you can recompile if you want. The issue is demonstrated by running `node runme.js` in the root dir of the project.

**Comment by elizarov** [comment] 2019-07-16 20:38
Thanks. I've reposted it here: https://youtrack.jetbrains.com/issue/KT-32708

**Comment by simon-alithya** [comment] 2021-08-23 18:25
Hi everyone,
Today i try this solution but i continue to have
i wrap my common function in the kotlin/js with promise like you show but i still have issue ?
some one have try it in his side ?
