### ISSUE TITLE
1.5.1-native-mt gets picked up by mvn versions:use-latest-versions

### ISSUE THREAD

**Issue by jnorthrup** [Kotlin/kotlinx.coroutines#2847] opened 2021-07-28 06:12 UTC
just a note that it looks like an unintended namespace overlap for the native suffix and the seemingly unrelated jvm version.

**Comment by qwwdfsad** [comment] 2021-07-28 09:56
Duplicate of https://github.com/Kotlin/kotlinx.coroutines/issues/2482

We aim to fix it with the new memory model and riddance of native-mt version

**Closed by qwwdfsad** 2021-07-28 09:56 UTC
