### ISSUE TITLE
Fatal exception in coroutines machinery for DispatchedContinuation

### ISSUE THREAD

**Issue by mwajeeh** [Kotlin/kotlinx.coroutines#2413] opened 2020-11-26 16:59 UTC
If I move `delay()` into another method then I get this exception. Strange thing is that I am unable to reproduce this in a smaller project. Code works fine if I create a new empty project with just the bare minimum code. 

```
    private fun playAnimation() {
        viewLifecycleOwner.lifecycleScope.launch {
            delay(100)
            delayAgain()// this function produces the exception
        }
    }
    suspend fun delayAgain() {
        delay(1000)
    }
```
A similar issue was reported here https://github.com/Kotlin/kotlinx.coroutines/issues/1909. 

My versions:
```
org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20
org.jetbrains.kotlin:kotlin-stdlib:1.4.10
org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.4
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.4
``` 
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Main [immediate], Continuation at <myMethod>$suspendImpl(<MyClass>.kt:52)@d50574a]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
        at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:315)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:122)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306)
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:175)
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:182)
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1484)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:316)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:398)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:100)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:172)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:122) 
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111) 
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306) 
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:175) 
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:182) 
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1484) 
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) 
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) 
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853) 
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825) 
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) 
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) 
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111) 
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306) 
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:316) 
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:398) 
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by mwajeeh** [comment] 2020-11-26 17:17
Updated few dependencies, still the same issue.
```
org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20
org.jetbrains.kotlin:kotlin-stdlib:1.4.20
org.jetbrains.kotlin:kotlin-stdlib-common:1.4.20
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.1
```

**Comment by qwwdfsad** [comment] 2020-11-26 17:42
Could you please provide a self-contained reproducer that I can run and debug?

Is this problem reproducible only on an emulated device or is it reproducible in unit-tests?

**Comment by mwajeeh** [comment] 2020-11-26 17:58
Issue is consistently reproducible in the bigger project I am working on but I have tried for several hours now to recreate this issue in a self contained bare minimum app but I am unable to do so as was the case with this https://github.com/Kotlin/kotlinx.coroutines/issues/1909.
I will share the code once I am able to reproduce it in a smaller project. It doesn't makes sense, all lib versions are same.

Problem is reproducible on emulator as well as Android device. This is not a unit test. @qwwdfsad

**Comment by yvolk** [comment] 2020-12-08 05:18
I'm observing the same exception on Android in kotlinx-coroutines-core-jvm-1.4.1.jar

I got this error myself once and two of not many (yet :-) ) users of my [Open source app](https://github.com/andstatus/game2048/blob/master/README.md#readme) reported this. Obviously the problem occurs relatively seldom, so I will think about some automated playing test to reproduce this...

```
2020-12-04 16:53:10.264 24118-24137/org.andstatus.game2048 E/AndroidRuntime: FATAL EXCEPTION: GLThread 8681
    Process: org.andstatus.game2048, PID: 24118
    kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[GameWindowCoroutineDispatcher, Continuation at com.soywiz.korge.tween.TweenKt$tween$3.invokeSuspend(tween.kt:149)@e8be942]){CompletedContinuation(result=kotlin.Unit, cancelHandler=InvokeOnCancel[@db09d53], onCancellation=null, idempotentResume=null, cancelCause=kotlinx.coroutines.JobCancellationException: TimeoutCoroutine has completed normally; job=TimeoutCoroutine(timeMillis=374){Completed}@5547690)}@4768b89. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:106)
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:383)
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0(GameWindow.kt:316)
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0$default(GameWindow.kt:313)
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:310)
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:81)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
     Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:226)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:106) 
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:383) 
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0(GameWindow.kt:316) 
        at com.soywiz.korgw.GameWindow.frame-o7-PVL0$default(GameWindow.kt:313) 
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:310) 
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:81) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259) 
```

**Comment by kam1sh** [comment] 2020-12-12 08:02
I also have same exception, but with Ktor:
```kotlin
    fun views(route: Route) {
        route.get("/") {
            val path = call.request.queryParameters["path"] ?: throw ApiException("No path provided.", "BAD_REQUEST")
            val size = call.request.queryParameters["size"]
            val asset = storage.get(path, size)
            asset.stream.use {
                call.respondOutputStream(contentType = ContentType.parse(asset.metadata.mimeType)) {
                    it.copyTo(this)
                }
            }
        }
    }
```
This often causes next stacktrace:
```
Exception in thread "eventLoopGroupProxy-3-2 @response-pipeline#10" Exception in thread "eventLoopGroupProxy-3-3 @response-pipeline#9" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[UnsafeBlockingTrampoline@75e08751, Continuation at io.ktor.utils.io.jvm.javaio.OutputAdapter$loop$1.loop(Blocking.kt:311)@433f844]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at io.ktor.utils.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:296)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:184)
	at io.ktor.utils.io.jvm.javaio.BlockingAdapter$end$1.resumeWith(Blocking.kt:163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.ktor.utils.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:296)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:184)
	at io.ktor.utils.io.internal.CancellableReusableContinuation.resumeWith(CancellableReusableContinuation.kt:93)
	at io.ktor.utils.io.ByteBufferChannel.resumeWriteOp(ByteBufferChannel.kt:2262)
	at io.ktor.utils.io.ByteBufferChannel.bytesRead(ByteBufferChannel.kt:909)
	at io.ktor.utils.io.ByteBufferChannel.consumed(ByteBufferChannel.kt:1952)
	at io.ktor.server.netty.cio.NettyResponsePipeline$processBodyFlusher$2.invokeSuspend(NettyResponsePipeline.kt:307)
	at io.ktor.server.netty.cio.NettyResponsePipeline$processBodyFlusher$2.invoke(NettyResponsePipeline.kt)
	at io.ktor.utils.io.ByteBufferChannel.lookAheadSuspend$suspendImpl(ByteBufferChannel.kt:1908)
	at io.ktor.utils.io.ByteBufferChannel.lookAheadSuspend(ByteBufferChannel.kt)
	at io.ktor.server.netty.cio.NettyResponsePipeline.processBodyFlusher(NettyResponsePipeline.kt:293)
	at io.ktor.server.netty.cio.NettyResponsePipeline.processJobs(NettyResponsePipeline.kt:470)
	at io.ktor.server.netty.cio.NettyResponsePipeline$processJobs$1.invokeSuspend(NettyResponsePipeline.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:216)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')

	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 28 more
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[UnsafeBlockingTrampoline@75e08751, Continuation at io.ktor.utils.io.jvm.javaio.OutputAdapter$loop$1.loop(Blocking.kt:311)@6d68fdb3]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at io.ktor.utils.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:296)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:184)
	at io.ktor.utils.io.jvm.javaio.BlockingAdapter$end$1.resumeWith(Blocking.kt:163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.ktor.utils.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:296)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:184)
	at io.ktor.utils.io.internal.CancellableReusableContinuation.resumeWith(CancellableReusableContinuation.kt:93)
	at io.ktor.utils.io.ByteBufferChannel.resumeWriteOp(ByteBufferChannel.kt:2262)
	at io.ktor.utils.io.ByteBufferChannel.bytesRead(ByteBufferChannel.kt:909)
	at io.ktor.utils.io.ByteBufferChannel.consumed(ByteBufferChannel.kt:1952)
	at io.ktor.server.netty.cio.NettyResponsePipeline$processBodyFlusher$2.invokeSuspend(NettyResponsePipeline.kt:307)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:216)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 22 more
```

I report it here, but I can duplicate it on Ktor YouTrack project if there is need in that.

Versions:
OS: Linux 5.3.18

JVM: 
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-suse-lp152.2.6.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.9+11-suse-lp152.2.6.2-x8664, mixed mode)
```
Kotlin: 1.4.21
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2
Ktor: 1.4.3

**Comment by floscher** [comment] 2020-12-21 15:10
I encountered the same issue with KTor as @kam1sh . Here is my minimal example: https://github.com/floscher/ktor-ClassCastException

The issue seems to occur when in [`call.respondOutputStream()`](https://api.ktor.io/1.4.3/io.ktor.response/respond-output-stream.html) or [`call.respondTextWriter()`](https://api.ktor.io/1.4.3/io.ktor.response/respond-text-writer.html) more than approx. 4080-4100 Bytes are written.

In this example serving up to 4088 Bytes is fine, more will throw the ClassCastException: https://github.com/floscher/ktor-ClassCastException/runs/1589576823#step:4:10131
On my machine the cutoff is at 4092 or 4093 Bytes most of the time.

[`call.respondText()`](https://api.ktor.io/1.4.3/io.ktor.response/respond-text.html) and [`call.respondBytes()`](https://api.ktor.io/1.4.3/io.ktor.response/respond-bytes.html) works fine though, so I'm using that for now as a workaround.

**Comment by qwwdfsad** [comment] 2020-12-21 15:45
Thanks for the reproducer! We'll investigate that

**Comment by floscher** [comment] 2020-12-21 17:02
This seems to be a regression introduced between KTor versions `1.4.1` and `1.4.2`/`1.4.3`:

https://github.com/floscher/ktor-ClassCastException/actions/runs/436231979 vs https://github.com/floscher/ktor-ClassCastException/actions/runs/436232262

**Comment by floscher** [comment] 2020-12-27 23:47
At least the problem with ktor seems to be fixed in Ktor `1.5.0`: https://github.com/floscher/ktor-ClassCastException/runs/1598543136?check_suite_focus=true#step:4:14043

**Comment by utybo** [comment] 2021-01-11 09:05
Can confirm that I randomly encountered this bug in Ktor on 1.4.3 while working on a server with large API JSON responses and that upgrading to 1.5.0 solved it

**Comment by qwwdfsad** [comment] 2021-01-25 16:21
Confirmed, it was a bug in Ktor, that was fixed in 1.5.0.

**Closed by qwwdfsad** 2021-01-25 16:21 UTC

**Comment by xuejingfei** [comment] 2021-03-01 12:33
> If I move `delay()` into another method then I get this exception. Strange thing is that I am unable to reproduce this in a smaller project. Code works fine if I create a new empty project with just the bare minimum code.
> 
> ```
>     private fun playAnimation() {
>         viewLifecycleOwner.lifecycleScope.launch {
>             delay(100)
>             delayAgain()// this function produces the exception
>         }
>     }
>     suspend fun delayAgain() {
>         delay(1000)
>     }
> ```
> 
> A similar issue was reported here #1909.
> 
> My versions:
> 
> ```
> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20
> org.jetbrains.kotlin:kotlin-stdlib:1.4.10
> org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10
> org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.4
> org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.4
> ```
> 
> ```
> kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Main [immediate], Continuation at <myMethod>$suspendImpl(<MyClass>.kt:52)@d50574a]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
>         at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
>         at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:315)
>         at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:122)
>         at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
>         at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306)
>         at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:175)
>         at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:182)
>         at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1484)
>         at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
>         at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
>         at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
>         at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
>         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
>         at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
>         at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306)
>         at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:316)
>         at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:398)
>         at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>      Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
>         at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:100)
>         at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
>         at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:172)
>         at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:122) 
>         at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111) 
>         at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306) 
>         at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:175) 
>         at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:182) 
>         at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1484) 
>         at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) 
>         at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) 
>         at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853) 
>         at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825) 
>         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111) 
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) 
>         at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) 
>         at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111) 
>         at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:306) 
>         at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:316) 
>         at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:398) 
>         at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19) 
>         at android.os.Handler.handleCallback(Handler.java:883) 
>         at android.os.Handler.dispatchMessage(Handler.java:100) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.app.ActivityThread.main(ActivityThread.java:7356) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
> ```
how to do solve  this question ，I have same question

**Comment by werner77** [comment] 2023-11-01 07:21
We are suffering from this error, using Ktor 2.3.1. I'm not sure if the issue is in Ktor because the stacktrace does not give enough info.

This force cast in the Kotlin code seems very suspicious though. Is there not a better way to do this? Even if some application misused the Coroutines API it should not result in such an obscure internal error right?

**Comment by rmcmk** [comment] 2024-10-08 19:01
> We are suffering from this error, using Ktor 2.3.1. I'm not sure if the issue is in Ktor because the stacktrace does not give enough info.
> 
> This force cast in the Kotlin code seems very suspicious though. Is there not a better way to do this? Even if some application misused the Coroutines API it should not result in such an obscure internal error right?

@werner77 
Did you ever land on a cause or find a fix? We are running into this same problem with Ktor 2.3.7
