### ISSUE TITLE
FastServiceLoader is not removed by R8

### ISSUE THREAD

**Issue by h6ah4i** [Kotlin/kotlinx.coroutines#3913] opened 2023-10-11 09:11 UTC
**Describe the bug**

Build fails when the `-checkdiscard class kotlinx.coroutines.internal.FastServiceLoader` rule is added to `proguard-rules.pro` in order to ensure the class is removed by R8.

I can see the same `-checkdiscard` rule found in the following test code file in this library, so I expected it should work.
https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/testdata/r8-test-rules.pro

**Provide a Reproducer**

Here is a minimal code to reproduce the issue;
https://github.com/h6ah4i/KotlinxCoroutinesR8OptimizationTest

Version info:
- `kotlinx.coroutines`: v1.7.3
- `R8`: 8.2.33 (build b9c6a503fec02920ce801cc886c748552851b6f3 from go/r8bot (luci-r8-custom-ci-focal-4-jc7u))

**Comment by dkhalanskyjb** [comment] 2023-10-16 08:20
I checked out your project, but I can't reproduce the issue with the Android plugin 8.3.0-alpha07 (to which Android Studio itself prompted me to upgrade): `:app:minifyDebugWithR8` passes without errors. This was probably already fixed in R8.

**Comment by h6ah4i** [comment] 2023-10-16 09:03
>  but I can't reproduce the issue with the Android plugin 8.3.0-alpha07

Thanks for your information! I also confirmed that the AGP v8.3.0-alpha07 has fixed this issue. I'll test this with more versions of AGP.


---

## [WIP] Compatibility check

| AGP version | R8 version | Result |
|---|---|---|
| 8.2.0-beta06 | 8.2.33 (build b9c6a503fec02920ce801cc886c748552851b6f3 from go/r8bot (luci-r8-custom-ci-focal-4-jc7u)) | :x:  |
| 8.3.0-alpha07 | 8.3.7-dev (build 3101ad6f74ee232528dfc66a2617a938384e66ea from go/r8bot (luci-r8-custom-ci-focal-18-ssis)) | :heavy_check_mark:  |

**Comment by h6ah4i** [comment] 2023-10-16 10:53
I have also reported this to Google's issue tracker;
https://issuetracker.google.com/issues/305545838

**Comment by dkhalanskyjb** [comment] 2023-10-16 11:43
It seems we as the coroutines library can't do anything about it, so I think we can close the issue. If some workaround for the affected version emerges (or it turns out we should make some specific edits to make it easier for R8 to optimize our code), feel free to write another comment here and ping me, and we'll discuss it further.

**Closed by dkhalanskyjb** 2023-10-16 11:43 UTC
Labels: bug
