### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: kotlinx.coroutines.CancellableContinuation.tryResume(Ljava/lang/Object;Ljava/lang/Object;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by MartinWong-H** [Kotlin/kotlinx.coroutines#3124] opened 2022-01-07 09:29 UTC
Kotlin 1.5.31 
kotlin.coroutines : 1.5.2-native-mt 

hi sir , when i upgrade kotlin version, and a task failure:

> Task :app:packageChinamainlandDebug FAILED
[Dva] check split cost 14
start make split bundles ......
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:packageChinamainlandDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)

Caused by: java.lang.NoSuchMethodError: kotlinx.coroutines.CancellableContinuation.tryResume(Ljava/lang/Object;Ljava/lang/Object;Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;
	at kotlinx.coroutines.sync.MutexImpl$LockCont.tryResumeLockWaiter(Mutex.kt:364)
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:322)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)  

i try to add  resolutionStrategy.force, but it can resolve problem:

configurations.all {
    resolutionStrategy.force 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2-native-mt'
}

**Comment by fvasco** [comment] 2022-01-07 09:39
Are you using the native version under the JVM?

**Comment by MartinWong-H** [comment] 2022-01-07 09:44
yes 
  org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2-native-mt

it cause error ?

**Comment by fvasco** [comment] 2022-01-07 09:49
I don't know, it's hard to reproduce without a reproducer.
However you should use a JVM version (1.5.2/1.6.0) on JVM.

**Comment by qwwdfsad** [comment] 2022-01-10 08:38
Hi, it's hard to tell what exactly is wrong without having an actual reproducer or detailed report.

I can only guess that you have a previous (1.2 I suppose) version of coroutines in the classpath. Gradle `--scan` can give you a few useful insights.

Closing as likely not caused by kotlinx.coroutines.

**Closed by qwwdfsad** 2022-01-10 08:38 UTC
Labels: waiting for clarification
