### ISSUE TITLE
Launch not executing code

### ISSUE THREAD

**Issue by p-v-d-Veeken** [Kotlin/kotlinx.coroutines#272] opened 2018-03-05 11:11 UTC
I think I'm hitting a weird Heisenbug with the `launch(CommonPool)` function.

The program I'm writing is highly dependent on coroutines and at any time there can be dozens of Jobs active simultaneously. In the tests I've written, launch(CommonPool) is called very often and the resulting Jobs are destroyed very quickly. One or more of tests occasionally, but not reliably, fail because the code inside of a launch block is quite simply not executing. 

I'm at a loss as to why this happens and I was hoping someone one here might have an idea what's going on? 

Kotlin version: 1.2.30
Coroutines version: 0.22.3

**Comment by jcornaz** [comment] 2018-03-05 13:33
Do you wait for the job completions in your tests ?

Examples: 
```kotlin
@Test fun testJoin() {
  var done = false
  val job = launch { done = true }

   // Make sure we can continue the test procedure by blocking until the job is done
  runBlocking { job.join() }

  // This will always succeed, because it is ensured that the job created by launch is completed
  assertTrue(done)
}

@Test fun testChildJob() {
  var done = false
  val job = launch {

    // child job
    launch(coroutineContext) { done = true }
  }

   // Make sure we can continue the test procedure by blocking until the job is done
   // Because there is a parent-child relation, the parent job will wait on the children before being completed
  runBlocking { job.join() }

  // This will always succeed, because it ensured that the jobs created by launch are completed
  assertTrue(done) 
}
```

**Comment by elizarov** [comment] 2018-05-16 09:59
I'm closing this one. Please provide additional info to reopen if the issue is still there.

**Closed by elizarov** 2018-05-16 09:59 UTC
Labels: question
