### ISSUE TITLE
SharedFlowImpl：java.lang.VerifyError 

### ISSUE THREAD

**Issue by TestPlanB** [Kotlin/kotlinx.coroutines#3612] opened 2023-02-01 02:24 UTC
java.lang.VerifyError: Verifier rejected class kotlinx.coroutines.CancellableContinuationImpl: java.lang.Throwable kotlinx.coroutines.CancellableContinuationImpl.OOO0(java.lang.Object): [0xFFFFFFFF] register index out of range (5 >= 4) (declaration of 'kotlinx.coroutines.CancellableContinuationImpl' appears in Anonymous-DexFile@0x76f1efa000-0x76f25d4de8)
	at kotlinx.coroutines.flow.SharedFlowImpl.findSlotsToResumeLocked(SharedFlowImpl.java:708)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlowImpl.java:321)

kotlinx-coroutine-core-jvm：1.4.1

**Comment by dkhalanskyjb** [comment] 2023-02-01 14:01
Looks like a duplicate of https://github.com/Kotlin/kotlinx.coroutines/issues/2931 In any case, this is most likely an issue with Android tooling, not the library.
Also, this is an old version of the library. Maybe upgrading it would help.

**Closed by dkhalanskyjb** 2023-02-01 14:01 UTC
Labels: bug
