### ISSUE TITLE
Exponential retry backoff on failure callback listener

### ISSUE THREAD

**Issue by isfaaghyth** [Kotlin/kotlinx.coroutines#1540] opened 2019-09-17 07:12 UTC
Hi, how can I exponential retry on `suspendCancellableCoroutine`? for example, I've case like this:

```kt
lateinit var result: Continuation<ObjectResponse>
lateinit var response: ObjectResponse

suspend fun OkHttpClient.webSocket(): ObjectResponse {
     val listener = object : WebSocketListener() {
          override fun open(socket: WebSocket, response: Response) {
               response = ObjectResponse(socket, response)
               result.resume(response)
          }
          override fun failure(socket: WebSocket, t: Throwable, response: Response?) {
               /* when a I got failure's websocket, I wanna exponential retry every 5 sec in here. */
          }
     }
     return suspendCancellableCoroutine { continuation ->
          newWebSocket(_, listener)
          result = continuation
     }
}
```

thanks!

**Comment by qwwdfsad** [comment] 2019-09-17 15:48
Depends on how exactly do you want to expose it in the API.
One approach is pretty straightforward (note: `Backoff` is not a coroutine primitive):

```
suspend fun OkHttpClient.webSocket(backoff: Backoff): ObjectResponse {
    while (backoff.shouldRetry()) {
        val listener = ...  // Listener just invokes resumeWith(failure(t))
        try {
            suspendCancellableCoroutine { ... }
        } catch (e: Throwable) {
            if (backoff.shouldRetry(e)) {
                delay(backoff.nextDelay())
            } else {
                throw e
            }
        }
    }
}
```

A more performant approach would be to re-schedule websocket listener from within a `WebSocketListener.failure` with a provided delay

**Comment by isfaaghyth** [comment] 2019-09-18 03:01
thanks, @qwwdfsad! but unfortunately, when I implement it, I got this exception when I use `.resumeWith(failure(t))`.
```
    java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[javax.net.ssl.SSLException: Read error: ssl=0x7ab6a1f8: I/O error during system call, Software caused connection abort]
        at kotlinx.coroutines.AbstractContinuation.resumeImpl(AbstractContinuation.kt:210)
        at kotlinx.coroutines.AbstractContinuation.resumeWith(AbstractContinuation.kt:141)
        at com.tokopedia.topchat.chatlist.viewmodel.EasyWsKt$easyWebSocket$listener$1.onFailure(WebSocketHelper.kt:47)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:216)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

this is my implementation:
```kt
lateinit var result: Continuation<ObjectResponse>
lateinit var response: ObjectResponse

suspend fun OkHttpClient.webSocket(): ObjectResponse {
    while (true) {
        val listener = object : WebSocketListener() {
            override fun open(socket: WebSocket, response: Response) {
                response = ObjectResponse(socket, response)
                result.resume(response)
            }
            override fun failure(socket: WebSocket, t: Throwable, response: Response?) {
                result.resumeWith(Result.failure(t))
            }
        }
        try {
            return suspendCancellableCoroutine { continuation ->
                result = continuation
                newWebSocket(request, listener)
            }
        } catch (e: Throwable) {
            retryIO { newWebSocket(request, listener) }
        }
    }
}

suspend fun <T> retryIO(
        times: Int = Int.MAX_VALUE,
        initialDelay: Long = 100, // 0.1 second
        maxDelay: Long = 5000,    // 5 second
        factor: Double = 2.0,
        block: suspend () -> T): T
{
    var currentDelay = initialDelay
    repeat(times - 1) {
        try {
            return block()
        } catch (e: IOException) {
            // you can log an error here and/or make a more finer-grained
            // analysis of the cause to see if retry is needed
        }
        delay(currentDelay)
        currentDelay = (currentDelay * factor).toLong().coerceAtMost(maxDelay)
    }
    return block() // last attempt
}
```

any idea for that?

thank in advance.

**Comment by qwwdfsad** [comment] 2019-09-18 09:11
Yes, in your `catch` block you invoke `newWebSocket` with the same listener that has a reference to **already resumed** continuation (one that thrown an exception and triggered your retry).
`retryIO` should not use the same listener

**Comment by isfaaghyth** [comment] 2019-09-18 09:59
so, what is the best way for that, @qwwdfsad?

**Comment by qwwdfsad** [comment] 2019-09-18 11:08
The best way is to check if you want to retry in `catch` block  and, if you want, go to the next iteration of the loop

**Comment by isfaaghyth** [comment] 2019-09-18 12:37
I've tried any possibilities (separate WebSocketListener, adding retry checker, etc.), but I'm still got this problem `java.lang.IllegalStateException: Already resumed,...`

**Comment by zach-klippenstein** [comment] 2019-09-18 16:47
You can only resume a continuation once, by design. Don't cache the continuation in a property, create the listen inside the `suspendCancellableCoroutine` block and use the fresh continuation each time.

**Comment by isfaaghyth** [comment] 2019-09-18 17:01
I've tried it like this:
```kt
suspend fun OkHttpClient.webSocket(): ObjectResponse {
    return suspendCancellableCoroutine { continuation ->
        val listener = object : WebSocketListener() {
            override fun onOpen(webSocket: WebSocket, response: Response) {
                ...
                continuation.resume(websocket)
            }

            override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) {
                continuation.resumeWith(Result.failure(t))
            }
            ...
        }
        newWebSocket(request, listener)
    }
}
```

but doesn't work, @zach-klippenstein. any suggestions for that?

**Comment by zach-klippenstein** [comment] 2019-09-18 19:52
Sure, combining your code and @qwwdfsad's:

```kotlin
suspend fun OkHttpClient.webSocket(backoff: Backoff): ObjectResponse {
  while (true) {
    try {
      return webSocket()
    } catch (e: Throwable) {
      if (backoff.shouldRetry(e)) {
        delay(backoff.nextDelay())
      } else {
        throw e
      }
    }
  }
}

// Converting the callbacks into suspend functions is unrelated from
// backoff logic – factor it out.
suspend fun OkHttpClient.webSocket(): ObjectResponse {
  // If your underlying API doesn't support cancellation, no point using
  // suspendCancellableCoroutine.
  return suspendCoroutine { continuation ->
    val listener = ContinuationListener(continuation)
    newWebSocket(request, listener)
  }
}

private class ContinuationListener(
  private val continuation: Continuation<ObjectResponse>
) : WebSocketListener() {
  override fun open(socket: WebSocket, response: Response) {
    // Don't store the response in some mutable property anywhere, it's unnecessary and makes
    // everything harder to reason about.
    val response = ObjectResponse(socket, response)
    result.resume(response)
  }

  override fun failure(socket: WebSocket, t: Throwable, response: Response?) {
    // Don't call resumeWith directly.
    result.resumeWithException(t)
  }
}
```

**Comment by isfaaghyth** [comment] 2019-09-19 08:20
thanks @zach-klippenstein! I've tried it, but still got this from logcat `java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[javax.net.ssl.SSLException: Read error: ssl=0x858085b8: I/O error during system call, Software caused connection abort]`

does my kotlin and coroutines version problems?
```gradle
kotlinVersion = "1.3.50"
coroutineVersion = '1.3.1'
```

this is my full code:
#### DataResponse.kt
```kt
class DataResponse(val webSocket: WebSocket, val response: Response) {
    val channel = Channel<WebSocketResponse>()
}
```

#### ContinuationListener.kt
```kt
class ContinuationListener(
        private val continuation: Continuation<DataResponse>
): WebSocketListener() {

    lateinit var _response: DataResponse

    override fun onOpen(webSocket: WebSocket, response: Response) {
        super.onOpen(webSocket, response)
        _response = DataResponse(webSocket, response)
        continuation.resume(_response)
    }

    override fun onFailure(webSocket: WebSocket, e: Throwable, response: Response?) {
        super.onFailure(webSocket, e, response)
        continuation.resumeWithException(e)
    }

    override fun onClosing(webSocket: WebSocket, code: Int, reason: String) {
        super.onClosing(webSocket, code, reason)
        webSocket.close(1000, "Bye!")
    }

    override fun onMessage(webSocket: WebSocket, text: String) {
        super.onMessage(webSocket, text)
        runBlocking {
            debug(TAG, " Message $text")
            _response.channel.send(text)
        }
    }

    override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
        super.onClosed(webSocket, code, reason)
        _response.channel.close()
    }

    companion object {
        const val TAG = "coroutineWebSocket"
    }
}
```

#### WebSocketHelper.kt
```kt
lateinit var result: CancellableContinuation<EasyWS>

suspend fun OkHttpClient.build(url: String, accessToken: String): DataResponse {
    var backoffTime = 1_000L
    while (true) {
        try {
            return webSocket(url, accessToken)
        } catch (e: Throwable) {
            delay(backoffTime)
            backoffTime *= 2
        }
    }
}

suspend fun OkHttpClient.webSocket(url: String, accessToken: String): DataResponse {
    return suspendCancellableCoroutine { continuation ->
        val request = ...
        val listener = ContinuationListener(continuation)
        newWebSocket(request, listener)
    }
}
```

**Comment by zach-klippenstein** [comment] 2019-09-19 14:59
Ah, I'm not super familiar with this websocket API but from the docs it seems like onFailure could be called before _or_ after onOpen. Probably need to do a check to see if you're getting the failure before then or after - you could use a CompletableDeferred instead of calling suspendCoroutine which lets you check if it's already completed. If you get the failure after open, you should cancel the channel instead of delivering through the DataResponse.

**Comment by qwwdfsad** [comment] 2019-09-20 18:55
Closing this, it's not the problem in `kx.coroutines`.
This question is now more relevant to StackOverflow

**Closed by qwwdfsad** 2019-09-20 18:55 UTC
Labels: question
