### ISSUE TITLE
Cannot figure out how to upgrade test to 1.6.0

### ISSUE THREAD

**Issue by connyduck** [Kotlin/kotlinx.coroutines#3138] opened 2022-01-13 20:32 UTC
I have a test for an Android ViewModel that uses androidx.paging. Basically it mocks the Api and then asserts that the Pager.flow returns the expected items.

I tried following the [Migration guide](https://github.com/Kotlin/kotlinx.coroutines/blob/1.6.0/kotlinx-coroutines-test/MIGRATION.md), but I cannot get it to work. `runTest` instead of `runBlocking`, is no problem. Both `StandardTestDispatcher` and `UnconfinedTestDispatcher` seem to do something different from what `TestCoroutineDispatcher` is doing, however. I also tried inserting `advanceUntilIdle()`, `runCurrent()` or `advanceTimeBy()` in between steps, to no avail.

Here is the test in question: https://github.com/tuskyapp/Tusky/blob/develop/app/src/test/java/com/keylesspalace/tusky/components/timeline/TimelineViewModelTest.kt

Any tips on how I can get this test, and maybe even the disabled one, to work with 1.6 and without deprecations is highly appreciated.

**Comment by dkhalanskyjb** [comment] 2022-01-14 08:11
Looks like a duplicate of https://github.com/Kotlin/kotlinx.coroutines/issues/3120. You do `collectLatest` here, which means that, if the execution order is changed, the result may also change because of new emissions canceling the block, which seems to be the root cause.

**Comment by connyduck** [comment] 2022-01-14 21:20
Yes seems similar.

I spent way too much time on this now, I tried `collectLatest` and other suggestions from #3120, but the only thing that makes a difference is the dispatcher. Giving up and sticking with `TestCoroutineDispatcher` for now.

**Comment by TreeFrogApps** [comment] 2022-01-17 14:42
Having similar issues after updating to 1.6.0 - whole large test suites now failing.  Using the `TestCoroutineDispatcher` resolves all failed tests ... I'll try and post a minimal example in another post.

**Comment by NitroG42** [comment] 2022-01-17 14:44
Be careful as the `TestCoroutineDispatcher` seems to behave differently between 1.5.2 and 1.6.0 versions, see here : https://github.com/NitroG42/Coroutine160Test

**Comment by dkhalanskyjb** [comment] 2022-01-17 16:30
@NitroG42, we tried very hard for `TestCoroutineDispatcher` not to be changed, and I was quite surprised by your discovery, so I tried copy-pasting the test module from 1.5.2 into your project and running the test with it: https://github.com/dkhalanskyjb/Coroutine160Test/commit/5bf782673f694cf75f40783d95e940be7c38d372 The only place where the project uses the new test module is in `Dispatchers.(re)setMain`. The test still fails, so I don't think `TestCoroutineDispatcher` is to blame here.

I think your example shows the problem with `TestCoroutineDispatcher` quite nicely: the tests that only work with `TestCoroutineDispatcher` are so brittle that even tiny changes to the implementations of the primitives will break the tests. Some other change in 1.6.0 must be causing the test to fail, though I can't say which one.

**Comment by NitroG42** [comment] 2022-01-17 16:52
No problem, I wrote this sample before understanding the last posts of #3120 .
It was hard at first because I basically expected that when my viewmodel would emit a value in a state flow, it would automatically call the test code with Turbine and awaitItem().
After some struggling I understand better now that if the same scenario would happens in the realworld, well the behavior would be exactly than the 1.6.0 version (conflated value).

**Closed** 2022-08-08 14:14 UTC
Labels: test
