### ISSUE TITLE
Suggestion: Document compatibility with Kotlin versions

### ISSUE THREAD

**Issue by jrgonzalezg** [Kotlin/kotlinx.coroutines#2732] opened 2021-05-27 14:32 UTC
When a new Kotlin version is released it is always unclear if the kotlinx.coroutines (which is usually updated later) is compatible with the new version or not. It would be nice if the README explicitly stated which versions of Kotlin is the last version of kotlinx.coroutines compatible with. Ideally that should be part or done at the same time than the rollout of the new Kotlin versions if the coordination for that is possible. For example right now there is Kotlin 1.5.10 and kotlinx.coroutines 1.5.0 which on README says it is a companion version for Kotlin 1.5.0. Does that mean that it has / may have issues if used with Kotlin 1.5.10? Should updates for Kotlin version in production code be delayed until kotlinx.coroutines companion for that version is released (when you are using both)?

I think right now it is always unclear if they are compatible or have expected / known issues and it would be good to be able to easily check compatibility on README when updating project dependencies.

**Comment by qwwdfsad** [comment] 2021-05-27 14:56
> it is always unclear if the kotlinx.coroutines is compatible with the new version or not

Kotlin has strict [backwards compatibility rules](https://kotlinlang.org/docs/language-committee-guidelines.html).
It basically states that _any_ library that was compiled by a previous version is fully compatible with the newer version unless stated otherwise. Such a rule is typically applicable for any mature enough ecosystem (e.g. Java, C++, Python 3+): the old code stays backwards compatible. Otherwise, it would'be been too much burden to re-release _every_ popular library with the newer version of the language.

**Comment by jrgonzalezg** [comment] 2021-05-27 16:08
Thanks!, so that means that most of the times we could assume old versions of kotlinx.coroutines are still fine to use with newer versions of Kotlin.

But there are still some things that are not compatible like what happened here: https://github.com/Kotlin/kotlinx.coroutines/issues/2649 Also, what do you mean by "unless stated otherwise"? Where will it be stated otherwise if that were the case?

**Comment by jrgonzalezg** [comment] 2021-05-27 16:11
Also, given the general rule, I think the wording on the README may be better if it were something like: "This is a companion version for the Kotlin >= 1.5.0 release" so it does not feel like it needs to match exactly.

**Comment by qwwdfsad** [comment] 2021-05-27 16:50
> what do you mean by "unless stated otherwise"? Where will it be stated otherwise if that were the case?

In that particular case, the incompatibility was caused by not one, but two compiler warnings. One stated that feature "inline classes" is experimental and can be changed in any release, the other one stated that `Duration` class is experimental and can be changed in any release. This is exactly what happened.

>This is a companion version for Kotlin releases >= 1.5.0"

By companion, we mean that the library was released with (has dependency on) the 1.5.0 version

**Closed** 2021-05-28 09:28 UTC
Labels: question
