### ISSUE TITLE
RxConvert defines multiple JvmName("from") methods with same signature

### ISSUE THREAD

**Issue by hrach** [Kotlin/kotlinx.coroutines#2284] opened 2020-10-07 06:46 UTC
Both Rx2 & Rx3 converters have redeclared name for Java to `from` for both `toObservable` and `toFlowable`. But these are two methods with only difference in their return type -> i.e. cannot be used from Java since it cannot resolve particular method.

- https://github.com/Kotlin/kotlinx.coroutines/blob/4c28f94ab69627303715d78bfb395c44603eeefd/reactive/kotlinx-coroutines-rx2/src/RxConvert.kt#L119
- https://github.com/Kotlin/kotlinx.coroutines/blob/4c28f94ab69627303715d78bfb395c44603eeefd/reactive/kotlinx-coroutines-rx2/src/RxConvert.kt#L154

**Comment by qwwdfsad** [comment] 2020-10-07 08:32
Thanks! It is a duplicate of #2182 that is being fixed right now targeting 1.4.0-M1

**Closed by qwwdfsad** 2020-10-07 08:32 UTC
