### ISSUE TITLE
ChannelAtomicCancelStressTest fails with CoroutinesInternalError caused by ClassCastException

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1588] opened 2019-10-01 11:22 UTC
https://teamcity.jetbrains.com/viewLog.html?buildId=2565122&buildTypeId=KotlinTools_KotlinxCoroutines_BuildWindows
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchReceiver$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:135)@7015c908]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#563998":StandaloneCoroutine{Cancelled}@7ed2297a]}@7aeda278. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:86)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:192)
	... 7 more
```

**Comment by elizarov** [comment] 2019-10-01 11:26
https://teamcity.jetbrains.com/viewLog.html?buildId=2555599&buildTypeId=KotlinTools_KotlinxCoroutines_BuildWindows
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)@54cd1478]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#567226":StandaloneCoroutine{Cancelled}@11cf9085]}@6477608b. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:86)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:192)
	... 7 more
```

**Comment by elizarov** [comment] 2019-10-01 11:34
https://teamcity.jetbrains.com/viewLog.html?buildId=2556063&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_Build#testNameId-3299188611556527194
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)@3ea5b47b]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#897075":StandaloneCoroutine{Cancelled}@7b38ff4b]}@50e96830. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:92)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:187)
	... 7 more
```

**Comment by elizarov** [comment] 2019-10-01 12:04
https://teamcity.jetbrains.com/viewLog.html?buildId=2554902&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_BuildWindows#testNameId-3299188611556527194
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
ava.lang.AssertionError
	at kotlinx.coroutines.channels.SendElement.tryResumeSend(AbstractChannel.kt:1055)
	at kotlinx.coroutines.channels.AbstractChannel$TryPollDesc.onPrepare(AbstractChannel.kt:684)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode$PrepareOp.perform(LockFreeLinkedList.kt:404)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode$AbstractAtomicDesc.prepare(LockFreeLinkedList.kt:472)
	at kotlinx.coroutines.selects.SelectBuilderImpl$AtomicSelectOp.prepare(Select.kt:567)
	at kotlinx.coroutines.internal.AtomicOp.perform(Atomic.kt:89)
	at kotlinx.coroutines.selects.SelectBuilderImpl.performAtomicTrySelect(Select.kt:541)
	at kotlinx.coroutines.channels.AbstractChannel.pollSelectInternal(AbstractChannel.kt:527)
	at kotlinx.coroutines.channels.AbstractChannel.registerSelectReceive(AbstractChannel.kt:705)
	at kotlinx.coroutines.channels.AbstractChannel.access$registerSelectReceive(AbstractChannel.kt:485)
	at kotlinx.coroutines.channels.AbstractChannel$onReceive$1.registerSelectClause1(AbstractChannel.kt:694)
	at kotlinx.coroutines.selects.SelectBuilderImpl.invoke(Select.kt:616)
	at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchReceiver$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:280)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
kotlinx.coroutines.CompletionHandlerException: Exception in cancellation handler for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)@72d8978c]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#564106":StandaloneCoroutine{Cancelling}@69c5a33b]}@2e5facbd
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:478)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:181)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1429)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1424)
	at kotlinx.coroutines.JobSupport.invokeOnCompletion(JobSupport.kt:1493)
	at kotlinx.coroutines.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:325)
	at kotlinx.coroutines.CancellableContinuationImpl.setupCancellation(CancellableContinuationImpl.kt:115)
	at kotlinx.coroutines.CancellableContinuationImpl.getResult(CancellableContinuationImpl.kt:226)
	at kotlinx.coroutines.channels.AbstractSendChannel.sendSuspend(AbstractChannel.kt:1108)
	at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:149)
	at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:280)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError
	at kotlinx.coroutines.channels.SendElement.tryResumeSend(AbstractChannel.kt:1055)
	at kotlinx.coroutines.channels.AbstractChannel$TryPollDesc.onPrepare(AbstractChannel.kt:684)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode$PrepareOp.perform(LockFreeLinkedList.kt:404)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode.getNext(LockFreeLinkedList.kt:92)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode.remove(LockFreeLinkedList.kt:238)
	at kotlinx.coroutines.RemoveOnCancel.invoke(CancellableContinuation.kt:297)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:171)
	... 22 more
```

**Comment by elizarov** [comment] 2019-10-01 13:54
https://teamcity.jetbrains.com/viewLog.html?buildId=2565287&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_BuildWindows
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)@1b1b1a34]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#563669":StandaloneCoroutine{Cancelled}@1e724a8a]}@475be4b. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:86)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:192)
	... 7 more
```

**Comment by elizarov** [comment] 2019-10-02 06:50
https://teamcity.jetbrains.com/viewLog.html?buildId=2566584&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_Build#testNameId-3299188611556527194
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchSender$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:108)@7920dc2b]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#1525850":StandaloneCoroutine{Cancelled}@3c225d6b]}@a7657db. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:86)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:192)
	... 7 more
```

**Comment by elizarov** [comment] 2019-10-02 06:52
https://teamcity.jetbrains.com/viewLog.html?buildId=2567101&tab=buildResultsDiv&buildTypeId=KotlinTools_KotlinxCoroutines_NightlyStress#testNameId-3299188611556527194
`ChannelAtomicCancelStressTest.testAtomicCancelStress[RendezvousChannel]`
```
otlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[ThreadPoolDispatcher[2, ChannelAtomicCancelStressTest], Continuation at kotlinx.coroutines.channels.ChannelAtomicCancelStressTest$launchReceiver$1.invokeSuspend(ChannelAtomicCancelStressTest.kt:135)@73114b46]){CancelledContinuation[kotlinx.coroutines.JobCancellationException: Job was cancelled; job="coroutine#21157923":StandaloneCoroutine{Cancelled}@64e06ece]}@52a44403. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:86)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:106)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:192)
	... 7 more
```

**Comment by qwwdfsad** [comment] 2019-10-08 12:50
Fixed in develop, was reproducible only in develop

**Closed by qwwdfsad** 2019-10-08 12:50 UTC

**Comment by debaj** [comment] 2020-03-10 08:58
The above crash log is reproducible in kotlinx.coroutines version 1.3.3 and 1.3.4

**Comment by elizarov** [comment] 2020-03-10 11:40
@debaj Can you elaborate? What environment was the code running in?

**Comment by anna-berezovskaya** [comment] 2020-03-10 11:54
@elizarov  It happens when the code, running inside coroutine, finishes. The coroutine was called from Java class like that: 
`BuildersKt.<Boolean>async(CoroutineScopeKt.CoroutineScope(coroutineContextProvider.defaultDispatcher()),
                                                      coroutineContextProvider.defaultDispatcher(), CoroutineStart.DEFAULT,
                                                      (coroutineScope, continuation) -> {
      suspendFunctionCall()                                                                                               }
                                                        return Unit.INSTANCE;
                                                      });`

**Comment by namig-accenture** [comment] 2020-06-16 22:41
@elizarov I am able to reproduce this on coroutines version 1.3.5.

```kotlin
fun main() {
    runBlocking {
        val f = flow<Int> {
            repeat(10){
                println("Emmiting $it")
                emit(it)
            }
        }

        launch {
            f.collect {
                delay(4000)
                println(it)
            }
        }
    }
}
```

Running the above code gives same excepton.
As far as I know, when the collector is busy the emit should be suspended however the above code snippet prints all without delay by throwing this exception on version 1.3.5.

**Comment by elizarov** [comment] 2020-06-17 14:13
How reliably it reproduces on your machine? Can you give more details on your setup, please: OS, CPU, Kotlin version, JDK version?

**Comment by namig-accenture** [comment] 2020-06-17 14:57
Hi @elizarov 
Thank you for your reply.

I think I get this error because I am using 
Intellij Idea 2018.2.8 with Kotlin plugin 1.3.20 with kotlin 1.3.20 with coroutines 1.3.5.

**Comment by elizarov** [comment] 2020-07-02 16:01
Recent versions of coroutines are not compatible with older versions of Kotlin.
