### ISSUE TITLE
Higher-order flow transform operator

### ISSUE THREAD

**Issue by sebek64** [Kotlin/kotlinx.coroutines#2650] opened 2021-04-15 08:52 UTC
I'm sorry if this is duplicate, but I couldn't find any similar issue already reported or the feature in the library or language that would provide this feature.

It would be convenient to have an operator of this form (and probably one can find a much better operator name)
```
@OptIn(ExperimentalTypeInference::class)
public fun <T, R> Flow<T>.generalFlowTransform(@BuilderInference operation: suspend FlowCollector<R>.(upstream: Flow<T>) -> Unit): Flow<R> {
    val upstream = this
    return flow {
        operation(upstream)
    }
}
```
Basically, it is a transform operator without the internal collect loop. In fact, that is probably the most general operator that allows to model any other operator.

The basic usage of this operator would be to achieve statefulness. Usually, you can achieve kind of that with operators like runningReduce, but often this is a more natural way.

**Comment by qwwdfsad** [comment] 2021-04-19 15:12
Duplicate of https://github.com/Kotlin/kotlinx.coroutines/issues/2580

**Closed by qwwdfsad** 2021-04-19 15:12 UTC
