### ISSUE TITLE
0.25 breaks compilation

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#517] opened 2018-08-25 22:42 UTC
Somehow, coroutines are being double packaged:
```
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: kotlinx.coroutines.experimental.InvokeOnCancellation
```

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/0b661fa28ada67983c6155730962be5f0e6d59ff
Setup: `./gradlew setup`
Upgrade the Coroutines version here: https://github.com/SUPERCILEX/Robot-Scouter/blob/0b661fa28ada67983c6155730962be5f0e6d59ff/buildSrc/src/main/kotlin/Config.kt#L25

**Comment by elizarov** [comment] 2018-08-26 17:55
This seems to be caused by the fact that Google tools do not support [JEP 238](http://openjdk.java.net/jeps/238) multi-release jars. I'm closing at a duplicate of #510. See it for tools versions that should fix the problem.

**Comment by SUPERCILEX** [comment] 2018-08-26 17:56
Gotya, thanks!

**Closed by elizarov** 2018-08-26 17:55 UTC
