### ISSUE TITLE
viewModelScope Unit Test: java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize

### ISSUE THREAD

**Issue by kevindesai777** [Kotlin/kotlinx.coroutines#1567] opened 2019-09-23 19:06 UTC
I am writing tests for viewModel scope that was newly released with AndroidX ViewModel 2.1.0

This is my test class: 

```
@ExperimentalCoroutinesApi
@RunWith(PowerMockRunner::class)
@PrepareForTest(ActionsModel::class, IGBCommunicator::class)
class PriorityNotificationBottomSheetViewModelTest {


    @Mock
    private lateinit var gbCommunicator: IGBCommunicator

    @Mock
    private lateinit var actionsModel: ActionsModel

    @Mock
    private lateinit var view: View

    @get:Rule
    var coroutineTestRule = CoroutineTestRule()

    @get:Rule
    val rule = InstantTaskExecutorRule()

    private lateinit var priorityNotificationBottomSheetViewModel: PriorityNotificationBottomSheetViewModel

    @Before
    fun setUp() {
        priorityNotificationBottomSheetViewModel = PriorityNotificationBottomSheetViewModel(gbCommunicator)
        priorityNotificationBottomSheetViewModel.setModel(actionsModel)
    }

    @Test
    fun testOnPositiveButtonClick() = coroutineTestRule.testDispatcher.runBlockingTest {
        priorityNotificationBottomSheetViewModel.onPositiveButtonClick(view)
        verify(gbCommunicator).priorityNotificationAPICall(actionsModel)
        assertEquals(priorityNotificationBottomSheetViewModel.dismissBottomSheetLiveData.await(), true)
    }
} 
```

This is the CoroutineTestRule class: 

```
@ExperimentalCoroutinesApi
class CoroutineTestRule(val testDispatcher: TestCoroutineDispatcher = TestCoroutineDispatcher()) : TestWatcher() {
    override fun starting(description: Description?) {
        super.starting(description)
        Dispatchers.setMain(testDispatcher)
    }

    override fun finished(description: Description?) {
        super.finished(description)
        Dispatchers.resetMain()
        testDispatcher.cleanupTestCoroutines()
    }
}
```

I have the latest versions of 
```
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.1'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1'
testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1")
testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.2.1'
```

I am getting an IllegalStateException
```
Exception in thread "main @coroutine#1" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:78)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:53)
```

Any ideas?

**Comment by qwwdfsad** [comment] 2019-09-24 14:38
Could you please provide a full stacktrace? What is the cause of `ISE`?

**Comment by qwwdfsad** [comment] 2019-12-13 13:30
Closing as outdated

**Closed by qwwdfsad** 2019-12-13 13:30 UTC
Labels: android, waiting for clarification
