### ISSUE TITLE
How to test all intermediate emissions despite conflation

### ISSUE THREAD

**Issue by lukas1** [Kotlin/kotlinx.coroutines#3120] opened 2022-01-04 07:42 UTC
Hi, I'm trying to test events posted to `MutableStateFlow`. I'd like to see that order of posting of those events is correct. However, documentation of StateFlow states: 

> Updates to the value are always conflated. So a slow collector skips fast updates, but always collects the most recently emitted value.

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/

And so, this test:
```kotlin
    @Test
    fun mutableStateFlowTest() = runTest(UnconfinedTestDispatcher()) {
        val testedFlow = MutableStateFlow(0)

        val testedValues = mutableListOf<Int>()
        testedFlow
            .onEach { testedValues.add(it) }
            .launchIn(this)

        flowOf(Unit)
            .onStart {
                testedFlow.update { it + 1 }
            }
            .onCompletion { testedFlow.update { it + 1 } }
            .onEach {
                testedFlow.update { it + 1 }
            }
            .launchIn(this)

        assertEquals(
            listOf(0, 1, 2, 3),
            testedValues
        )
    }

```

fails. `testedValues` is `[0, 3]`. That is, it contains only two values first value and the last.

While this is understandable in the light of what the documentation says, I would still like to be able to check that all events were sent to the state flow in the order that I sent them.

But in the real application, I do like the conflation, because indeed it doesn't make sense to redraw UI after every single update to the state flow, if updates are faster than redrawing is.

The reason I'd like to check for the order of emitted events in tests is, if for nothing else, then at least for the fact, that if conflation can occur during tests, it makes tests unstable. A little change in code could mean, that some event will get conflated and the test will be broken, even if the change itself should not change which events are being emitted.

Is there any way to make the test above work? It works with the deprecated `TestCoroutineDispatcher` and `runBlockingTest`. 

I have tried this, which works:

```kotlin
class ImmediateTestDispatcher : CoroutineDispatcher() {
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        block.run()
    }
}

    @Test
    fun mutableStateFlowTest() = runBlocking(ImmediateTestDispatcher()) {
        val testedFlow = MutableStateFlow(0)

        val testedValues = mutableListOf<Int>()
        val job = testedFlow
            .onEach { testedValues.add(it) }
            .launchIn(this)

        flowOf(Unit)
            .onStart {
                testedFlow.update { it + 1 }
            }
            .onCompletion { testedFlow.update { it + 1 } }
            .onEach {
                testedFlow.update { it + 1 }
            }
            .launchIn(this)

        assertEquals(
            listOf(0, 1, 2, 3),
            testedValues
        )
        job.cancel()
    }
```
But in practice, this is not very practical approach.

As a background, the example above is a very simplified example of something, that occurs in tests of our application. With the old `TestCoroutineDispatcher` those tests work correctly, collecting all the events, but with the new test dispatchers from `1.6.0`, tests are broken.

I don't want to rewrite every single one of the test cases to account for these skipped values (it's almost 200 test cases that are broken) and as I said, I do think that in context of tests, all events should be recorded anyway, because if I account for the skipped events now, maybe later I might make a change, that will cause some of those skipped events appear again. That would be very brittle.

Thanks.

**Comment by lukas1** [comment] 2022-01-04 07:52
btw the `ImmediateTestDispatcher` approach does work with my actual test cases, but again, that is probably a lucky chance. Also, having that kind of Dispatcher doesn't help with use cases where `delay()` etc is used in the tested code.

**Comment by Bezkarpie** [comment] 2022-01-04 18:03
I fidgeted a bit with it and from what I understand:

As UnconfinedTestDispatcher doesn't ensure any order of performing tasks, keeping everything under this one Unconfined dispatcher is expected to give you bad results here.

`Like Dispatchers.Unconfined, this one does not provide guarantees about the execution order when several coroutines are queued in this dispatcher.`

But it also is supposed to resume its coroutines immediately without going through dispatch, you actually also have an example of using it for StateFlow testing in documentation of UnconfinedTestDispatcher

`Another typical use case for this dispatcher is launching child coroutines that are resumed immediately, without going through a dispatch; this can be helpful for testing Channel and StateFlow usages.`

So I suppose what you want to do is run the collection of the flow with an UnconfinedTestDispatcher, but the rest of the test, the code that is emitting, under a StandardTestDispatcher that lets you precisely control the order of execution

That would leave you with something like this:

```@Test
    fun mutableStateFlowTest() = runTest(StandardTestDispatcher()) {
        val testedFlow = MutableStateFlow(0)
        val testedValues = mutableListOf<Int>()

        val job = testedFlow
            .onEach { testedValues.add(it) }
            .launchIn(this + UnconfinedTestDispatcher())

        flowOf(Unit)
            .onStart { testedFlow.update { it + 1 } }
            .onCompletion { testedFlow.update { it + 1 } }
            .onEach { testedFlow.update { it + 1 } }
            .launchIn(this)

        runCurrent()

        assertEquals(
            listOf(0, 1, 2, 3),
            testedValues
        )

        job.cancel()
    }
```

I'm not awfully familiar with StateFlow and new testing mechanics yet, so somebody stronger in this topic could elaborate on the importance of sharing the testScheduler in that scenario (I'll see more about it tomorrow too :) )

**Comment by lukas1** [comment] 2022-01-05 06:20
Ok I understand your suggestion, but if that's the case, I simply don't want to stop using `TestCoroutineDispatcher` and I am greatly unhappy about it being deprecated then. 

I'm sure there are some confusing scenarios with the `TestCoroutineDispatcher`, but for the usual case it produces much better results.

Right now I'd have to redo almost 200 test cases in our code base to fit the new APIs somewhat, making tests unreadable (there would have to be way more `runCurrent()` statements, one will not cut it in many cases.

And what do I get back for the rework? Nothing.

And I'd be rewriting it into something that uses experimental APIs, so that I get the joy of rewriting those 200 test cases again, if the team decides to change the API again.

**Comment by Bezkarpie** [comment] 2022-01-05 09:46
I understand your frustration, I'm somewhat guilty of using experimental api in production too, but we were explicitly warned about it being experimental

If you re satisfied with old api, I'd recommend you just stick to it despite being deprecated.

Regarding multiple calls of `runCurrent()` there's a chance what could help you is `advanceUntilIdle()` of `TestCoroutineScheduler`

**Comment by lukas1** [comment] 2022-01-10 06:46
Anyway the approach with `StandardTestDispatcher` is broken if the tested flow is converted to `LiveData` (which is what I ultimately need)

I've tried this:

```kotlin
    fun mutableStateFlowTest() = runTest(StandardTestDispatcher()) {
        val testedFlow = MutableStateFlow(0)
        val testedValues = testedFlow.asLiveData(UnconfinedTestDispatcher()).testObservedEvents()

        flowOf(Unit)
            .onStart { testedFlow.update { it + 1 } }
            .onCompletion { testedFlow.update { it + 1 } }
            .onEach { testedFlow.update { it + 1 } }
            .launchIn(this)

        runCurrent()

        assertEquals(
            listOf(0, 1, 2, 3),
            testedValues
        )
    }
```

which returns [0, 1, 3] (skips 2)

This could entirely be my own failure of understanding the new APIs, but I'm unable to make this example with `LiveData` work no matter what.

**Comment by lukas1** [comment] 2022-01-10 06:55
I think the issue is, that `Flow<T>.asLiveData` has this line in it:
```kotlin
val scope = CoroutineScope(Dispatchers.Main.immediate + context + supervisorJob)
```

But neither `StandardTestDispatcher` nor `UnconfinedTestDispatcher` are immediate dispatchers. So that's where this gets broken I think.

**Comment by ReginFell** [comment] 2022-01-10 12:46
We also encounter the same issue with 1.6.0. 

```
val progressFlow = MutableStateFlow(false)

fun invokeApiCall() {
  viewModelScope.launch {
progressFlow.value = true 
//invokeMockedApi without any delay
progressFlow.value = false
  }
}
```

when you collect, you receive only `false`, when it used to collect `false`, `true`, `false`. So not it's not clear how to test intermid states

**Comment by lukas1** [comment] 2022-01-10 13:58
@ReginFell 

If you don't need to handle delays, check out the implementation of `ImmediateCoroutineDispatcher` in my first comment. If you set it as main dispatcher, using `Dispatchers.setMain(ImmediateCoroutineDispatcher())`, it will work.

This is not documented anywhere and it is not the official recommended way to do this (I don't know what is the official way if there even is any in the first place), but it definitely works.

Unfortunately this will not work if you have delays in your coroutines, because this dispatcher does not handle delays. One could try to implement delays by themselves, but the IDE will warn you that you're trying to use internal coroutine API's which is discouraged.

My view is, that either the `TestCoroutineDispatcher` should not be deprecated or we need another type of dispatcher apart from the provided `StandardTestDispatcher` and `UnconfinedTestDispatcher`, one that will immediately execute blocks.

Alternatively you have to change your tests to account for conflation (documentation of `StateFlow` clearly states, that conflation is to be expected), but that leads to brittle test cases, as it is not going to be easily predictable when conflation will occur and when it will not.

I think something like `TestCoroutineDispatcher` is simply needed.

**Comment by lukas1** [comment] 2022-01-10 14:31
Also one more thing. 

While the example by @Bezkarpie works, it does not reflect reality of at least our code base, and probably also not other codebases.

In @Bezkarpie example the state flow needs to be collected by `UnconfinedTestDispatcher()`, while the flow that fills data into the state flow needs to run on `StandardTestDispatcher`. 

I couldn't get it to work any other way (this could be my own failing entirely).

Often that's not what we want.

Since in at least in context of android development, we rely on `viewModelScope`, which internally uses `Dispatchers.Main.immediate`.

If we're also using things, such as `asLiveData()`, which internally also relies on `Dispatchers.Main.immediate`, basically it is impossible/impractical to have separate dispatcher for collecting the State Flow (collected as `LiveData` using `asLiveData()`) and a dispatcher for launching coroutines in view model, that fill the state flow.

It would mean that every single coroutine that is launched in view model using `viewModelScope.launch {}` would have to be updated to launch the coroutine from an injected `StandardTestDispatcher` (and only `StandardTestDispatcher`, `UnconfinedTestDispatcher` will not work).

But that's not how we want to have our code structured, it's a lot of boilerplate and it shouldn't be necessary. It wasn't necessary with the old test APIs.

**Comment by NitroG42** [comment] 2022-01-10 14:37
Is the 1.6.0 implementation of TestCoroutineDispatcher still working for you ? 
I have a "simple" test for an Android app, which unfortunatelly (because i'm not sure how to do it otherwise) is using viewModelScope, and I have a different behavior between 1.5.2 (success) and 1.6.0 (failure).
I'm not using delay either. 
Working on a sample right now.

**Comment by joffrey-bion** [comment] 2022-01-10 14:37
> Is there any way to make the test above work? It works with the deprecated TestCoroutineDispatcher and runBlockingTest.

@lukas1 I don't quite understand the disappointment here, nor the need for the old behaviour. The tests as written here don't seem deterministic. You are launching 2 coroutines, not waiting for anything, and then hoping to have the results in a list that you update concurrently.

Making this test work by dispatcher magic (unconfined, immediate, and the likes) really doesn't seem like the right way to approach the problem IMO. The test just doesn't read well in the first place. If I see `launch` I don't expect immediate execution in tests anymore than in production.

If you want to force other coroutines execution, you should use facilities like `runCurrent` and `advanceUntilIdle` as part of the test, which makes it read better because we see what's going on.

> A little change in code could mean, that some event will get conflated and the test will be broken, even if the change itself should not change which events are being emitted.
> (...)
> if I account for the skipped events now, maybe later I might make a change, that will cause some of those skipped events appear again. That would be very brittle.

Relying on dispatcher is just as brittle as that. Adding suspension points in production code could change the behaviour too and break those tests. I'm not arguing that you should account for skipped events, I'm saying that you should make sure all events happen by inserting `runCurrent` or `advanceUntilIdle` in appropriate places, and the current state of tests is not doing that

**Comment by lukas1** [comment] 2022-01-10 14:54
> you should make sure all events happen by inserting runCurrent or advanceUntilIdle

This does not work however; If you have example such as the one provided by @ReginFell , using `runCurrent()` will conflate the state to the last state. So `StandardTestDispatcher` does not help.

> or just test the last state

Again, this is not appropriate. Again the example by @ReginFell shows precisely why we don't want to just test for the last state; We want to make sure that the state update happens. That it is not accidentally skipped by wrong implementation.

It's not possible/practical to add suspension points before EVERY update to the state flow.

> Relying on special dispatcher implementations is just as brittle as that.

I disagree. Relying on documented dispatcher behaviour is precisely what we should do. There should be a specific dispatcher that guarantees order of execution as if the code was completely blocking. If that were the case, there'd be no confusion about order of execution or anything.

> The test just doesn't read well in the first place.

Actually it reads much better than suggested alternatives with using `runCurrent()`. Because the resulting code is pretty much the same, but additional dance around dispatchers is needed, which was NOT needed before. The tests up until now were very easy to read.

**Comment by lukas1** [comment] 2022-01-10 14:59
@NitroG42 I also had some such tests, that stopped working even with the deprecated `TestCoroutineScope`. I think the issue in those failing tests was when trying to read latest value from `StateFlow`.

I plan to study these cases more closely, as I do not know what exactly is going on there, why it fails, but at least for now I was able to fix those cases by using the `ImmediateCoroutineDispatcher` that I have posted in this thread. I'm not sure if it's the right solution, but since it works, that's what I ended up with for now. I want to research this further though.

**Comment by Bezkarpie** [comment] 2022-01-10 15:13
@lukas1 @ReginFell 
Honestly, I can't see where's the impossible to solve issue you are experiencing.
I checked @ReginFell example, which doesn't unfortunately include an example for failing test - it would be really helpful if you include failing test code 

Anyway, I ended up with something like this, I also checked some simple delays and it works ok:

    @Before
        fun setUp() {
            Dispatchers.setMain(StandardTestDispatcher())
        }
  
      @After
      fun tearDown() {
          Dispatchers.resetMain()
      }
  
      @Test
      fun testVM() = runTest {
          val viewModel = ExampleViewModel()
          val results = mutableListOf<Boolean>()
  
          val job = viewModel.progressFlow
              .onEach { results.add(it) }
              .launchIn(this + UnconfinedTestDispatcher(testScheduler))
  
          viewModel.invokeApiCall()
  
          advanceUntilIdle()
  
          assertEquals(
              listOf(false, true, false),
              results
          )
  
          job.cancel()
      }
  
      class ExampleViewModel : ViewModel() {
          val progressFlow = MutableStateFlow(false)
  
          fun invokeApiCall() {
              viewModelScope.launch {
                  delay(2000)
                  progressFlow.value = true
                  delay(2000)
                  progressFlow.value = false
              }
          }
      }

And it works just fine.
I agree that it could be prettier, you might try to write some wrapping code to reduce boilerplate
But it *does* work as far as I am concerned 
With the same exact solution as I proposed previously, without any need to pass a dispatcher to launch inside the viewModel (which is a standard since a long time as far as I am concerned anyway)

If you re experiencing any issues that can not be solved with it, please, provide a full minimal example including the test and tested code
I'm happy to help and explore the topic as I'm curious myself
But I have to see something that's not working with current mechanics first

**Comment by lukas1** [comment] 2022-01-10 15:15
@Bezkarpie 

this works because you added `delay` into `ExampleViewModel`. Take it out and see how it works.

Also, add another property `val progressFlowAsLiveData = progressFlow.asLiveData()` and test values from that

**Comment by Bezkarpie** [comment] 2022-01-10 15:17
Please, put this in your IDE and check it first before making such statements.

**Comment by NitroG42** [comment] 2022-01-10 15:31
Just did a sample project about the Android ViewModel issue : https://github.com/NitroG42/Coroutine160Test
I think it also fits here as I'm not sure how to test all the emissions with the new API (I will use this project as a trial to make the test works, but in my trial it always ended with different issues).

**Comment by lukas1** [comment] 2022-01-10 16:17
@Bezkarpie 

I apologize, I should have tested it before making the comment. I responded in a haste.

That said, I have created an example where the approach using `StandardTestDispatcher` fails, but `TestCoroutineDispatcher` works.

It's a very simplified example of something that happens in our application a lot. 

Again, it is possible, that I'm using the new APIs wrong.

Here's the example:

```kotlin
class DummyTest {
    @Test
    fun dummyTest() {
        ArchTaskExecutor.getInstance()
            .setDelegate(object : TaskExecutor() {
                override fun executeOnDiskIO(runnable: Runnable) = runnable.run()

                override fun postToMainThread(runnable: Runnable) = runnable.run()

                override fun isMainThread(): Boolean = true
            })
        val testScheduler = TestCoroutineScheduler()
        Dispatchers.setMain(StandardTestDispatcher(testScheduler))
        //Dispatchers.setMain(UnconfinedTestDispatcher(testScheduler))
        //Dispatchers.setMain(TestCoroutineDispatcher())

        val collectedStates = mutableListOf<DummyViewModel.State>()

        val viewModel = DummyViewModel(flowOf(3))

        viewModel.stateAsLiveData.observeForever {
            collectedStates.add(it)
        }

        viewModel.runTest()
        testScheduler.runCurrent()

        assertEquals(
            listOf(
                DummyViewModel.State(),
                DummyViewModel.State(
                    isLoading = true,
                    data = null
                ),
                DummyViewModel.State(
                    isLoading = true,
                    data = 3
                ),
                DummyViewModel.State(
                    isLoading = false,
                    data = 3
                ),
            ),
            collectedStates
        )

        Dispatchers.resetMain()
    }


    class DummyViewModel(
        private val dataFlow: Flow<Int>
    ) : ViewModel() {
        data class State(
            val isLoading: Boolean = false,
            val data: Int? = null
        )

        private val stateFlow = MutableStateFlow(State())
        val stateAsLiveData = stateFlow.asLiveData()

        fun runTest() {
            dataFlow
                .onStart { stateFlow.update { it.copy(isLoading = true) } }
                .onCompletion { stateFlow.update { it.copy(isLoading = false) } }
                .onEach { current -> stateFlow.update { it.copy(data = current) } }
                .launchIn(viewModelScope)
        }
    }
}
```

This test works fine if you comment out the line with `StandardTestDispatcher` set as Main dispatcher and uncomment instead the line that uses `TestCoroutineDispatcher`. I've also tried `UnconfinedTestDispatcher` although I had no reason to think that that approach would work.

Let me know if you have some ideas how to make my example work, please. In the meantime I will try to also come up with some solution.

Thank you for your time.

**Comment by lukas1** [comment] 2022-01-10 16:23
@Bezkarpie btw indeed you approach works if testing the `StateFlow` directly. But with the `asLiveData()` in the mix, it does not work.

**Comment by lukas1** [comment] 2022-01-10 16:37
@joffrey-bion 

> I guess it would help to see the real life application of those tests

Please take a look at my example code above. Maybe you have some idea how to structure this test better with `StandardTestDispatcher` that would avoid issues with conflation? Thanks.

**Comment by lukas1** [comment] 2022-01-10 16:43
after some trial and error, I was able to make this work:

```kotlin
class DummyTest {
    @Test
    fun dummyTest() = runTest {
        ArchTaskExecutor.getInstance()
            .setDelegate(object : TaskExecutor() {
                override fun executeOnDiskIO(runnable: Runnable) = runnable.run()

                override fun postToMainThread(runnable: Runnable) = runnable.run()

                override fun isMainThread(): Boolean = true
            })
        val testScheduler = TestCoroutineScheduler()
        Dispatchers.setMain(StandardTestDispatcher(testScheduler))
        //Dispatchers.setMain(UnconfinedTestDispatcher(testScheduler))
        //Dispatchers.setMain(TestCoroutineDispatcher())

        val collectedStates = mutableListOf<DummyViewModel.State>()

        val viewModel = DummyViewModel(
            flow {
                delay(100)
                emit(3)
                delay(100)
            }
        )

        viewModel.stateAsLiveData.observeForever {
            collectedStates.add(it)
        }

        viewModel.runTest()

        testScheduler.advanceUntilIdle()
        testScheduler.runCurrent()

        assertEquals(
            listOf(
                DummyViewModel.State(),
                DummyViewModel.State(
                    isLoading = true,
                    data = null
                ),
                DummyViewModel.State(
                    isLoading = true,
                    data = 3
                ),
                DummyViewModel.State(
                    isLoading = false,
                    data = 3
                ),
            ),
            collectedStates
        )

        Dispatchers.resetMain()
    }

    class DummyViewModel(
        private val dataFlow: Flow<Int>
    ) : ViewModel() {
        data class State(
            val isLoading: Boolean = false,
            val data: Int? = null
        )

        private val stateFlow = MutableStateFlow(State())
        val stateAsLiveData = stateFlow.asLiveData()

        fun runTest() {
            dataFlow
                .onStart { stateFlow.update { it.copy(isLoading = true) } }
                .onCompletion { stateFlow.update { it.copy(isLoading = false) } }
                .onEach { current -> stateFlow.update { it.copy(data = current) } }
                .launchIn(viewModelScope)
        }
    }
}
```

The relevant changed part is actually this:

```kotlin
        val viewModel = DummyViewModel(
            flow {
                delay(100)
                emit(3)
                delay(100)
            }
        )
```

Adding a `delay` before and after `emit`. It's a bit weird, but it does simulate at least somewhat real life situations. So maybe this is the solution.

I find it ugly though, so whenever possible, I'd probably stick with my `ImmediateCoroutineDispatcher`, as it is much simpler to use. What do you guys think?

**Comment by joffrey-bion** [comment] 2022-01-10 17:14
Thanks for sharing actual code, I guess I would use the test flow provided as `dataFlow` to control the test here.

For instance, use a channel to control when the source flow emits and completes:

```kotlin
class MockSourceFlow<T> {

    private val channel = Channel<T>()

    val flow = channel.consumeAsFlow()

    suspend fun simulateData(value: T) {
        channel.send(value)
    }

    fun simulateCompletion(throwable: Throwable? = null) {
        channel.close(throwable)
    }
}
```

And then force other coroutines to run before checking intermediate state updates:

<details>
  <summary>Click to expand the test implementation</summary>
```kotlin
class DummyTest {

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun dummyTest() = runTest {
        ArchTaskExecutor.getInstance().setDelegate(object : TaskExecutor() {
            override fun executeOnDiskIO(runnable: Runnable) = runnable.run()
            override fun postToMainThread(runnable: Runnable) = runnable.run()
            override fun isMainThread(): Boolean = true
        })
        Dispatchers.setMain(StandardTestDispatcher(testScheduler))

        val testDataSource = MockSourceFlow<Int>()
        val viewModel = DummyViewModel(testDataSource.flow)
        viewModel.stateAsLiveData.observeForever {}

        advanceUntilIdle()
        assertEquals(DummyViewModel.State(), viewModel.stateAsLiveData.value)

        viewModel.runTest()
        advanceUntilIdle()

        val expectedLoadingStateNoValue = DummyViewModel.State(
            isLoading = true,
            data = null
        )
        assertEquals(expectedLoadingStateNoValue, viewModel.stateAsLiveData.value)

        testDataSource.simulateData(3)
        advanceUntilIdle()

        val expectedLoadingStateWithValue = DummyViewModel.State(
            isLoading = true,
            data = 3
        )
        assertEquals(expectedLoadingStateWithValue, viewModel.stateAsLiveData.value)

        testDataSource.simulateCompletion()
        advanceUntilIdle()

        val expectedCompletedStateWithValue = DummyViewModel.State(
            isLoading = false,
            data = 3
        )
        assertEquals(expectedCompletedStateWithValue, viewModel.stateAsLiveData.value)

        Dispatchers.resetMain()
    }


    class DummyViewModel(
        private val dataFlow: Flow<Int>
    ) : ViewModel() {
        data class State(
            val isLoading: Boolean = false,
            val data: Int? = null
        )

        private val stateFlow = MutableStateFlow(State())
        val stateAsLiveData = stateFlow.asLiveData()

        fun runTest() {
            dataFlow
                .onStart { stateFlow.update { it.copy(isLoading = true) } }
                .onCompletion { stateFlow.update { it.copy(isLoading = false) } }
                .onEach { current -> stateFlow.update { it.copy(data = current) } }
                .launchIn(viewModelScope)
        }
    }
}
```
</details>

This is what I mean by not brittle. I don't believe you should use immediate dispatchers to work around the expected behaviour of state flows, but rather make it explicit in the test that what you want is to assume other coroutines have progressed at this point in the test, and then assert. This also allows you to verify that the value you're expecting in the live data is actually there when you expect it to be.

**Comment by joffrey-bion** [comment] 2022-01-10 17:22
It is slightly longer indeed, but it also is more accurate. It will assert the proper things at the proper time, and when it fails you'll see exactly at which point, which can't be said with the single-list-assert approach

**Comment by dkhalanskyjb** [comment] 2022-01-12 08:52
Hi! I'm the maintainer of the test module, so direct the criticisms here.

Thank you @joffrey-bion for handling this! Everything's pretty much as you say.

An official way to test channels, `MutableStateFlow`, `Flow`, etc., without conflating/dropping intermediate values is by launching the collecting side in `UnconfinedTestDispatcher(testScheduler)`, like @Bezkarpie suggested. This way, the sending operations will "themselves" ensure the delivery of the elements to the collecting side, and the conflation does not happen. If you needed to reliably observe immediate values in production, you would need to do roughly the same with `Dispatchers.Unconfined` or `Dispatchers.Main.immediate`.

Adding delays to emulate context switches between different coroutines is also a fine approach, as is using `advanceUntilIdle` or `advanceTimeBy` to strategically ensure that the other coroutines finished their current portion of the work.

A guiding principle for the new API was that tests should somehow reflect how the code would behave in production. In contrast, no actual dispatchers (I think?) behave exactly like `TestCoroutineDispatcher` does.  This led to code working or not working in tests not reflecting how it would run in production, so many people avoided the test module in favor of `runBlocking` (though not being able to use `withContext` from `runBlockingTest` also contributed to this).

The code in the opening post now fails, and this is intentional, because, if we look at it with fresh eyes, it *should* fail: one wouldn't observe this behavior in real life consistently, and one wouldn't observe it at all unless in a multithreaded dispatcher.

All that said, we're open to introducing something with the behavior equivalent to `TestCoroutineDispatcher` if there are good reasons to keep it, but we haven't seen good arguments in its favor yet.

**Comment by dkhalanskyjb** [comment] 2023-11-13 14:34
The master issue for this topic is now #3939, closing this one in its favor.

**Closed by dkhalanskyjb** 2023-11-13 14:34 UTC
Labels: flow, test
