### ISSUE TITLE
A proposal for `awaitAny` and `joinAny`

### ISSUE THREAD

**Issue by ShreckYe** [Kotlin/kotlinx.coroutines#3664] opened 2023-03-07 16:30 UTC
I'd like to propose a set of `awaitAny` and `joinAny` functions, which serve as counterparts to `awaitAll`s and `joinAll`s and are shortcuts to `select` in some cases. They can easily be implemented with `select` like this:

```kotlin
suspend fun <T> awaitAny(vararg deferreds: Deferred<T>): T =
    select { deferreds.forEach { it.onAwait { it } } }

suspend fun <T> Collection<Deferred<T>>.awaitAny(): T =
    select { forEach { it.onAwait { it } } }

suspend fun joinAny(vararg jobs: Job): Unit =
    select { jobs.forEach { it.onJoin { it } } }

suspend fun Collection<Job>.joinAny(): Unit =
    select { forEach { it.onJoin { it } } }
```

**Comment by JakeWharton** [comment] 2023-03-07 16:36
See #2867. Your implementation allows losing coroutines to continue to do work despite their result never being used.

**Comment by dkhalanskyjb** [comment] 2024-04-12 14:23
Yep, duplicate of #2867

**Closed by dkhalanskyjb** 2024-04-12 14:23 UTC
Labels: enhancement
