### ISSUE TITLE
Can't use `TestCoroutineDispatcher` with `stateIn()`

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#2722] opened 2021-05-21 08:45 UTC
Consider this code : 

```
@Test
fun `with delay`() {
    val testCoroutineDispatcher = TestCoroutineDispatcher()
    val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

    Dispatchers.setMain(testCoroutineDispatcher)

    testCoroutineScope.runBlockingTest {

        val uiStateFlow = flow {
            emit(1)
            delay(500)
            emit(2)
        }.mapLatest { integer ->
            integer.toString()
        }.stateIn(
            scope = CoroutineScope(SupervisorJob() + testCoroutineDispatcher),
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = ""
        )

        testCoroutineDispatcher.advanceTimeBy(1_000)

        val result = uiStateFlow.first()

        assertEquals("2", result) // fails !! result = "1"
    }

    Dispatchers.resetMain()
    testCoroutineScope.cleanupTestCoroutines()
}
```

To my knowledge, it is impossible to set the `Dispatcher` a `StateFlow` is using. This is due to the fact the `SharingConfig` has an `EmptyCoroutineContext` (`Share.kt:189` with coroutine version to 1.5.0). 

Is this a bug or ~~a feature~~ intended ?

If this is intended, how could we "manipulate time" with the `TestCoroutineDispatcher`, using a `StateFlow` ?

**Comment by dkhalanskyjb** [comment] 2021-05-21 09:54
> To my knowledge, it is impossible to set the `Dispatcher` a `StateFlow` is using.

Did you try `flow {...}.mapLatest {...}.flowOn(TestCoroutineDispatcher).stateIn {...}`? The context that is being set in `Share.kt` determines in which dispatcher `flow.collect` will be called, but if `flowOn(ctx)` is used, the emissions are expected to happen in `ctx`.

**Comment by NinoDLC** [comment] 2021-05-21 10:58
Yes, `flowOn()` doesn't change anything (before or after `map`)

**Comment by dkhalanskyjb** [comment] 2021-05-21 11:22
Ok, I looked at this more closely. `flowOn` does change the execution context of the `flow`, but the problem is that no emissions ever happen until `uiStateFlow.first()`. According to the [docs on `WhileSubscribed`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-sharing-started/-while-subscribed.html), sharing is only started (and the flow starts being collected) when the first subscribed appears. Changing the test not to use `runBlockingTest` but `runBlocking` and replacing `advanceTimeBy` by a simple `delay` shows that advancing/waiting after creating the `StateFlow` does nothing.

**Comment by NinoDLC** [comment] 2021-05-21 12:25
Thank you for your time. So, is it a bug or a feature ? I don't really understand your answer. 

Also, according to what your say, shouldn't this code work ? 

```
@Test
fun `with delay`() {
    val testCoroutineDispatcher = TestCoroutineDispatcher()
    val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

    Dispatchers.setMain(testCoroutineDispatcher)

    testCoroutineScope.runBlockingTest {

        val uiStateFlow = flow {
            emit(1)
            delay(500)
            emit(2)
        }.mapLatest { integer ->
            integer.toString()
        }.flowOn(testCoroutineDispatcher).stateIn(
            scope = CoroutineScope(SupervisorJob() + testCoroutineDispatcher),
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = ""
        )

        uiStateFlow.collect {
            testCoroutineDispatcher.advanceTimeBy(1_001)

            assertEquals("2", it) // still fails !! result = "1"
        }
    }

    Dispatchers.resetMain()
    testCoroutineScope.cleanupTestCoroutines()
}
```

**Comment by dkhalanskyjb** [comment] 2021-05-21 12:31
I don't know what particular behavior you are asking about, but I don't see any bugs here.

The new code also shouldn't work. I added one line (which shouldn't affect anything) to clarify why:
```kotlin
@Test
fun `with delay`() {
    val testCoroutineDispatcher = TestCoroutineDispatcher()
    val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

    Dispatchers.setMain(testCoroutineDispatcher)

    testCoroutineScope.runBlockingTest {

        val uiStateFlow = flow {
            emit(1)
            delay(500)
            emit(2)
        }.mapLatest { integer ->
            integer.toString()
        }.flowOn(testCoroutineDispatcher).stateIn(
            scope = CoroutineScope(SupervisorJob() + testCoroutineDispatcher),
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = ""
        )

        uiStateFlow.collect {
            println("it already has the value $it") // <---------------------- added this line
            testCoroutineDispatcher.advanceTimeBy(1_000)

            assertEquals("2", it) // still fails !! result = "1"
        }
    }

    Dispatchers.resetMain()
    testCoroutineScope.cleanupTestCoroutines()
}
```
`advanceTimeBy` only executes after `it` already has a value assigned to it. It would be impossible for `uiStateFlow` to change the value of `it` on the fly; it may call the passed function block later with the value `"2"`, but at this point of time, the block is already processing the value `"1"`, as can be seen by the added `print`.

**Comment by NinoDLC** [comment] 2021-05-21 12:51
I understand, thank. Such a weird behavior that collecting a Flow start changing its value. Is this quantum world ?

To sum it up, there's no other way to test the fact that after a 500ms delay, the `StateFlow` should expose "2" ?
```
@Test
fun `with delay`() {
    val testCoroutineDispatcher = TestCoroutineDispatcher()
    val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

    Dispatchers.setMain(testCoroutineDispatcher)

    testCoroutineScope.runBlockingTest {

        val uiStateFlow = flow {
            emit(1)
            delay(500)
            emit(2)
        }.mapLatest { integer ->
            integer.toString()
        }.stateIn(
            scope = testCoroutineScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = ""
        )

        val firstResult = uiStateFlow.first() // <-- This needs to happen to "start the coroutine"
        assertEquals("1", firstResult)

        testCoroutineDispatcher.advanceTimeBy(500)

        val secondResult = uiStateFlow.first()
        assertEquals("2", secondResult)
    }

    Dispatchers.resetMain()
    testCoroutineScope.cleanupTestCoroutines()
}
```

**Comment by dkhalanskyjb** [comment] 2021-05-21 13:08
You can launch a `collect` in parallel to force the flow to start emitting, or use `SharingStarted.Eagerly`, which would cause the `StateFlow` to start emitting immediately:
```kotlin
            val uiStateFlow = flow {
                emit(1)
                delay(500)
                emit(2)
            }.mapLatest { integer ->
                integer.toString()
            }.stateIn(
                scope = testCoroutineScope,
                started = SharingStarted.Eagerly,
                initialValue = ""
            )
            testCoroutineDispatcher.advanceTimeBy(550)
            assertEquals("2", uiStateFlow.first())
```
`flowOn()` is not needed because the `scope` that you're passing to `stateIn` already includes the `TestCoroutineDispatcher` in the context, so the flow is being executed there—so, the code you provided initially did have the right execution context. I initially misunderstood the problem and thought that the flow that you're dealing with has its own execution context, in which case, `flowOn` would be the way to modify it, but in your case, setting `scope` is sufficient; sorry for the misdirection!

**Comment by dkhalanskyjb** [comment] 2021-05-21 13:11
About the quantum world: nah, it's fairly intuitive once you internalize the concept that flows are cold, that is, they only describe the rules for how to produce values, no code is actually executed when you define a flow. Sharing a flow does execute the given flow, and `SharingStarted` defines when exactly the flow is executed.

**Comment by NinoDLC** [comment] 2021-05-21 13:47
Thanks a lot for your time. 

This is fairly more complex than using a simple `liveData {}` block to launch a coroutine inside a ViewModel so I guess our team will stay with the LiveData approach to communicate with the View until a simpler way to test (other than injecting Dispatcher and SharingStarted strategy).

**Closed** 2024-04-12 08:31 UTC
Labels: test, flow-sharing
