### ISSUE TITLE
kotlinx-coroutines-test:1.6.1 - stateIn and sharedIn (that are not started while subscribed) are not practical to test with runTest

### ISSUE THREAD

**Issue by AlexDochioiu** [Kotlin/kotlinx.coroutines#3323] opened 2022-06-16 13:03 UTC
Background info: `runTest` won't finish unless all the coroutines launched inside also finished. This is what I'd expect for most cases but it becomes problematic if I want something along the lines of:
```kotlin
val uiState = myFlow
        .stateIn(viewModelScope, SharingStarted.Eagerly, UiStates.Empty)
```
The problem is that `runTest` will hang and time out because of the job started by `stateIn`/`shareIn` which is kept active until `viewModelScope` is canceled.

**Comment by dkhalanskyjb** [comment] 2022-06-17 08:17
Duplicate of https://github.com/Kotlin/kotlinx.coroutines/issues/3287.

**Closed by dkhalanskyjb** 2022-06-17 08:17 UTC
