### ISSUE TITLE
Exception in coroutine after cancel is silently ignored

### ISSUE THREAD

**Issue by spand** [Kotlin/kotlinx.coroutines#386] opened 2018-06-07 08:54 UTC
I am a bit unsure if this is by design but exceptions can end up being silently ignored in a case like this:

```    var selfJob: Job? = null
    @Test
    fun `Self cancel eats exception`() = runBlocking {
        selfJob = launch(coroutineContext) {
            selfJob!!.cancel()
            throw Exception("Silenced")
        }
    }
```

It took me some time to figure out that this was the case, and I would expect to be notified somehow. I can see the design rationale of ignoring exceptions after cancel, but at the very least I would like to have some additional notification if `-Dkotlinx.coroutines.debug` is specified.

**Comment by jcornaz** [comment] 2018-06-07 09:53
In my opinion, it could be a rational design, because when job does not complete, we can have only one cause. And in this case the primary cause of the non-completion is cancellation.

But what bother me is the fact the it is not consistent with the behavior of `async`.

```kotlin
val job = async {
  coroutineContext[Job]!!.cancel()
  throw Exception("something went wrong")
}

job.await() // throw Exception (something went wrong)
```

```kotlin
val job = launch(CoroutineExceptionHandler { _, exception ->
  println(exception) // catch JobCancellationException (Job was cancelled normally)
}) {
  coroutineContext[Job]!!.cancel()
  throw Exception("something went wrong")
}

job.join()
```

**Comment by qwwdfsad** [comment] 2018-06-07 10:11
This is indeed a bug, duplicate of one of #333 subtasks.
In the new design, `Exception("something went wrong")` always will be passed to the exception handler.

It cannot be really a rational design, because losing exceptions is always an undesired behaviour (and tend to piss off people who run production systems :) ).
E.g. consider more complicated case 
```
launch() {
launch {
    try {
        doSomeProductionStuff()
    }
    finally {
        cleanupResources()
    }
}
}
```

If `cleanupResources` resources throws (or even worse, throws only when job is cancelled or completed exceptionally), then this exception **should** be reported, otherwise it may lead to unpleasant side effects

**Closed by qwwdfsad** 2018-06-07 10:11 UTC
