### ISSUE TITLE
Runblocking high cpu usage on linuxX64

### ISSUE THREAD

**Issue by 89jd** [Kotlin/kotlinx.coroutines#2926] opened 2021-09-10 12:57 UTC
I am trying out the new memory model for kotlin and I am getting 100% cpu on a core all the way through when using delay and runBlocking (seems similar to below):

https://github.com/Kotlin/kotlinx.coroutines/issues/1225

```
  private val scope = CoroutineScope(Dispatchers.Default + Job())
  
  fun main(args: Array<String>) {
      runBlocking {
          scope.launch {
           println("Loop")
              delay(1000)
          }.join()
      }
  }
```

This is sample code that causes it. Strangely building for linuxarm32 (I built coroutines from source); doesn't have the same issue.

If I change the code to be: -

```
  private val scope = CoroutineScope(Dispatchers.Default + Job())
  
  fun main(args: Array<String>) {
      scope.launch {
          println("Loop")
          delay(1000)
      }
  
      while(true) {
          usleep(1000000/5)
      }
  }
```

CPU usage is almost 0%. Assumedly something is going wrong with delaying in runblocking thread?

I am using version 1.5.1-new-mm-dev1

**Comment by 89jd** [comment] 2021-09-10 14:14
Found a fix is to run 
```
runBlocking(Dispatchers.Main/Dispatchers.Default) {

}
```

**Comment by dkhalanskyjb** [comment] 2021-09-16 08:36
Hi! Thanks for the report. I couldn't reproduce this with the latest code—could you please check if the issue persists on `1.5.1-new-mm-dev2`?

**Comment by qwwdfsad** [comment] 2021-09-21 11:51
It was a bug in`mm-dev1` that is already fixed in sources and `mm-dev2`

**Closed by qwwdfsad** 2021-09-21 11:51 UTC
