### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method loadList(Lkotlin/coroutines/Continuation;)Ljava/lang/Object; in class MyClass

### ISSUE THREAD

**Issue by vishnyakov-aleks** [Kotlin/kotlinx.coroutines#775] opened 2018-10-30 15:38 UTC
Kotlin 1.3
Coroutines 1.0.0

When i building app with release type - i have a crash

> Process:
> 
>  com.cr.android, PID: 2924
>     java.lang.IllegalAccessError: Method 'java.lang.Object com.cr.android.layers.BasePagingPresenter.loadList(kotlin.coroutines.Continuation)' is inaccessible to class 'com.cr.android.layers.places.MyPlacesPresenter$loadPage$$inlined$loadPageJob$1$1' (declaration of 'com.cr.android.layers.places.MyPlacesPresenter$loadPage$$inlined$loadPageJob$1$1' appears in /data/app/com.cr.android-43kSW8W_kPNuNDpWhxC7Lg==/base.apk)
>         at com.cr.android.layers.places.MyPlacesPresenter$loadPage$$inlined$loadPageJob$1$1.invokeSuspend(BasePagingPresenter.kt:30)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
>         at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
>         at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
>         at kotlinx.coroutines.scheduling.Task.run(Tasks.kt:94)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:732)`
> 

Part of crashable code:
`abstract class BasePagingPresenter<T, E: BasePagingView> : BasePresenter<E>() where T : PaginationItem {
    var nextPageId: Int = 1
    val list = ArrayList<PaginationItem>()

    protected abstract suspend fun loadList(): BaseResponse

    abstract fun loadPage()
    abstract fun loadNextPage()

    protected inline fun <reified successResponseClass> loadPageJob()
            where successResponseClass : BasePaginationResponse<T> = GlobalScope.launch (Main) {
        viewState.onLoadListStarted()
        val response = withContext(IO) { loadList() }
        viewState.onLoadListFinished()
`
But when i building it with debug sign - all fine...
Please help me

**Comment by vishnyakov-aleks** [comment] 2018-10-31 09:39
After invalidate cache and restart i received this exception

> java.lang.IllegalAccessError: Method 'java.lang.Object com.c.android.layers.BasePagingPresenter.loadList(kotlin.coroutines.Continuation)' is inaccessible to class 'com.c.android.layers.places.MyPlacesPresenter$loadPage$$inlined$loadPageJob$1$1' 

I removed "protected" from fun loadList() and it now works fine...

I think, suspend functions need warning, if they are protected or...

**Comment by qwwdfsad** [comment] 2018-10-31 09:42
It looks like a bug in a jettifier.
Could you please post a sample project so we will have a self-contained reproducer and will be able to report it to Google?

Making a method `protected` indeed makes the compiler to generate additional stuff.

**Comment by qwwdfsad** [comment] 2018-11-06 11:04
Hi, any update on that?

**Comment by elizarov** [comment] 2019-02-22 16:10
Closing as obsolete

**Closed by elizarov** 2019-02-22 16:10 UTC
Labels: waiting for clarification

**Comment by mcastagnolo** [comment] 2019-03-15 00:40
@elizarov Can you post a link to why this is obsolete now for others who are searching for information on this exception?

**Comment by elizarov** [comment] 2019-03-15 07:26
@mcastagnolo Do you have steps to reproduce this exception with modern versions of libraries and toolchains? If yes, please share here and we'll reopen the issue.

**Comment by mrugacz95** [comment] 2019-06-10 09:01
Kotlin 1.3.31
Coroutines 1.1.1

@elizarov 
Hi, I have encountered the same problem.
Overloading suspend method in other module throws exception:
```
Process: pl.snowdog.myapplication, PID: 5668
    java.lang.NoSuchMethodError: No virtual method method(ILkotlin/coroutines/Continuation;)Ljava/lang/Object; in class Lpl/snowdog/lib/MyLibraryClass; or its super classes (declaration of 'pl.snowdog.lib.MyLibraryClass' appears in /data/app/pl.snowdog.myapplication-bui9d-YNvsaFOGJakfhyxw==/base.apk!classes3.dex)
        at pl.snowdog.myapplication.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6748)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
As [RadekJ](https://stackoverflow.com/users/2318843/radekj) mentioned [here](https://stackoverflow.com/questions/52037520/kotlin-coroutines-nosuchmethoderror-when-calling-overriden-suspended-function) adding `implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.25.0'` in module solves problem.

I've add sample Android project with this issue:
[myapp.zip](https://github.com/Kotlin/kotlinx.coroutines/files/3271344/myapp.zip)

**Comment by elizarov** [comment] 2019-06-10 09:08
Hm. You sample app uses a mix of `1.1.1` version for its `app` and `1.2.1` for the `lib`. Can you try to reproduce it with an application that consistently uses the most recent stable version (`1.2.1`), please?

**Comment by mrugacz95** [comment] 2019-06-11 11:35
Unfortunately, even if application uses `org.jetbrains.kotlinx:kotlinx-coroutines-core` with version `1.2.1` and `lib` doesn't have this dependency, there is still the same error. I still have to add `coroutines-core` to `lib` dependencies to make it work.
