### ISSUE TITLE
Add optional CoroutineStart parameter to launchIn

### ISSUE THREAD

**Issue by pacher** [Kotlin/kotlinx.coroutines#2571] opened 2021-03-08 19:50 UTC
`launchIn` is a convenient shortcut, but can't be used if a `start` parameter of `launch` needs to be provided.
Shall we add an optional `start` to `launchIn`? I was wondering why not and why it is not already there.

My use case (probably similar to [this](https://github.com/Kotlin/kotlinx.coroutines/issues/1393#issuecomment-767899374)):
I am not advanced user and trying to stay away from `Unconfined` and `Undispatched`, but I guess I am finally in a situation where I should use the latter.
I have a hot source which currently is still reactor `Flux` (not yet migrated to flow), let's call it `flux`.
```kotlin
flux()
   .asFlow()
   .onEach { ... }
   .launchIn(scope)

action()
```
Here `action` indirectly modifies the source `flux`. I need to be sure that by the time `action` is called subscription to source flux has happened and no emissions are lost between `launch` and `action`. 
Do I understand correctly that I just need to `launchIn(scope, start = CoroutineStart.UNDISPATCHED`) to be safe?

**Comment by qwwdfsad** [comment] 2021-03-12 14:19
Yes, `UNDISPATHCED` would do the trick as long as you don't have any non-trivial operators in between, e.g. `buffer` that actually launches a separate coroutine for flow collection. 

Thanks for the use-case! I will close this as a duplicate of #1326, but will reconsider its status, keeping additional demand on it in mind

**Closed by qwwdfsad** 2021-03-12 14:19 UTC
Labels: flow
