### ISSUE TITLE
.shareIn() operator causes InvalidMutabilityException in Kotlin/Native (1.4.2-native-mt)

### ISSUE THREAD

**Issue by PetarMarijanovic** [Kotlin/kotlinx.coroutines#2445] opened 2020-12-11 14:12 UTC
**Version:** `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2-native-mt`

**Expected:**

- Ability to store `SharedFlow` created by `.shareIn()` in a field

**Actual:**

- Using `.shareIn()` freezes the upstream upon creation
- The upstream might capture the internal state of the object and, by doing so, freezes the whole object even before it was fully initialized
- `InvalidMutabilityException: mutation attempt of frozen Main` is thrown because `sharedFlow` field is being initialized but `Main` is already frozen by `.shareIn()`

**Test:**
```Kotlin
    @Test
    fun test() = runTest {

        class Main {

            val i = 42

            val sharedFlow: Flow<Int> = // InvalidMutabilityException: mutation attempt of frozen Main
                flow { emit(i) }
                    .shareIn(
                        CoroutineScope(Dispatchers.Default),
                        SharingStarted.WhileSubscribed(stopTimeoutMillis = 1000, replayExpirationMillis = 0),
                        replay = 1
                    )
        }

        val main = Main() 
        assertEquals(main.i, main.sharedFlow.first())
    }
```

**Real world example:**
```Kotlin
class Repository(api: Api) {

    private val networkRequest =
        flow { emit(api.fetchSomething()) }
            .shareIn(
                CoroutineScope(Dispatchers.Default),
                SharingStarted.WhileSubscribed(stopTimeoutMillis = 1000, replayExpirationMillis = 0),
                replay = 1
            )

    fun data(): Flow<Response> = networkRequest
}
```

**Comment by TrevorStoneEpic** [comment] 2021-02-05 21:38
I'm running into this as well. Have you found a workaround to get shareIn working at all?

**Comment by petarmarijanovicfive** [comment] 2021-02-05 23:58
Unfortunately no

**Comment by TrevorStoneEpic** [comment] 2021-02-07 19:42
Hey @petarmarijanovicfive 
I was able to find a workaround!

So from your test, it can be re-written ever so slightly as below (adding this@Main to the i call in flow{}.
```kotlin
 @Test
    fun test() = runTest {

        class Main {

            val i = 42

            val sharedFlow: Flow<Int> = // InvalidMutabilityException: mutation attempt of frozen Main
                flow { emit(this@Main.i) }
                    .shareIn(
                        CoroutineScope(Dispatchers.Default),
                        SharingStarted.WhileSubscribed(stopTimeoutMillis = 1000, replayExpirationMillis = 0),
                        replay = 1
                    )
        }

        val main = Main() 
        assertEquals(main.i, main.sharedFlow.first())
    }
```
I am not aware of the internals but I am guessing what is happening is that for the `this` to be valid using shareIn it must freeze `this` which is then causing the problem you're seeing.

I found that if you are able to remove the implicit reference to `this` you can make it work! Instead of freezing Main it will freeze the value inside of the new scoping.

```kotlin
 @Test
    fun test() = runTest {

        class Main {

            val i = 42

            val sharedFlow: Flow<Int> = // InvalidMutabilityException: mutation attempt of frozen Main
             i.let { i ->
                    flow { emit(i) }
                        .shareIn(
                            CoroutineScope(Dispatchers.Default),
                            SharingStarted.WhileSubscribed(stopTimeoutMillis = 1000, replayExpirationMillis = 0),
                            replay = 1
                        )
                }
        }

        val main = Main() 
        assertEquals(main.i, main.sharedFlow.first())
    }
```


If you need two values in the scope you can use a pair with (x to y).let
If you need more it seems the best case is to make a holder data class that can then contain the values.

Hopefully this helps you out. I would assume that this bug will most likely not be fixed until the new memory model, but I hope we see otherwise. Until then these minor changes might solve your issue

**Comment by petarmarijanovicfive** [comment] 2021-02-16 11:13
Hey, @TrevorStoneEpic I tried out both of your proposals, and none work for me. I still get an InvalidMutabilityException

**Comment by TrevorStoneEpic** [comment] 2021-02-16 15:05
That's unfortunate. Can you paste the test code you're trying. This fix has still been working well for me

**Comment by petarmarijanovicfive** [comment] 2021-02-16 15:33
Yes, I was really hoping that I have a workaround for this. I used your examples and runned the tests on `ios` and `macos` environments. Both crash

**Comment by qwwdfsad** [comment] 2021-03-01 15:11
Unfortunately, it is not a bug, but a limitation of the current Native memory model.
`flow { emit(i) }` in the constructor captures `this`, all captured references are frozen (`shareIn` launches a coroutine and thus freezes the lambda in `flow`) and then the result cannot be assigned to the `val sharedFlow`.

The only workaround is not to capture this, e.g. `i.let { it -> ...}` provided by @TrevorStoneEpic

**Closed by qwwdfsad** 2021-03-01 15:11 UTC
Labels: native
