### ISSUE TITLE
KotlinJS - CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@2, [object Object]]

### ISSUE THREAD

**Issue by nbransby** [Kotlin/kotlinx.coroutines#1287] opened 2019-06-21 15:51 UTC
This error happens 1.3.30+ including 1.3.40, but there is no error in 1.3.21. It seems the compiler generates incorrect JS, the line that errors occurs is:
```
return closure$continuation.$$coroutineResult$$.user;
```
which causes `TypeError: Cannot read property 'user' of undefined` 

Full trace:
```
CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@2, [object Object]]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers; caused by IllegalStateException: Job DeferredCoroutine{Cancelled}@1 is already complete or completing, but is being completed with CompletedExceptionally[JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property 'user' of undefined; job=DeferredCoroutine{Cancelled}@1]; caused by JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property 'user' of undefined; job=DeferredCoroutine{Cancelled}@1
	at DispatchedContinuation.DispatchedTask.handleFatalException_mseuzz$ (c:\code\TeamHub\vscode-extension\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:2785:16)
	at DispatchedContinuation.DispatchedTask.run (c:\code\TeamHub\vscode-extension\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:2778:10)
	at Timeout._onTimeout (c:\code\TeamHub\vscode-extension\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:28050:17)
	at ontimeout (timers.js:427:11)
	at tryOnTimeout (timers.js:289:5)
	at listOnTimeout (timers.js:252:5)
	at Timer.processTimers (timers.js:212:10)
```

```
TypeError: Cannot read property 'user' of undefined
	at Coroutine$retryOnNetworkError.local$function (c:\code\TeamHub\vscode-extension\node_modules\@teamhub\core\index.js:3607:55)
	at Coroutine$retryOnNetworkError.doResume (c:\code\TeamHub\vscode-extension\node_modules\@teamhub\core\index.js:1395:25)
	at retryOnNetworkError (c:\code\TeamHub\vscode-extension\node_modules\@teamhub\core\index.js:1451:23)
	at Coroutine$onboardUserIfNecessaryAsync$lambda.doResume (c:\code\TeamHub\vscode-extension\node_modules\@teamhub\core\index.js:3755:31)
	at Coroutine$await_0.CoroutineImpl.resumeWith_tl1gpc$ (c:\code\TeamHub\vscode-extension\node_modules\kotlin\kotlin.js:27964:35)
	at JobSupport$AwaitContinuation.DispatchedTask.run (c:\code\TeamHub\vscode-extension\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:2758:22)
	at Timeout._onTimeout (c:\code\TeamHub\vscode-extension\node_modules\kotlinx-coroutines-core\kotlinx-coroutines-core.js:28050:17)
	at ontimeout (timers.js:427:11)
	at tryOnTimeout (timers.js:289:5)
	at listOnTimeout (timers.js:252:5)
	at Timer.processTimers (timers.js:212:10)
```

**Comment by qwwdfsad** [comment] 2019-06-21 16:43
It is definitely a compiler bug.
But it is hard to report it to the compiler team without an actual reproducer, could you please attach it?

**Comment by nbransby** [comment] 2019-06-22 14:35
I believe its caused by a inline extension with the following signature 
```
internal suspend inline fun <T, R> T.retryOnNetworkError(function: T.() -> R): R
```
It seems T is undefined inside the function arg
Removing inline fixes it.

**Comment by qwwdfsad** [comment] 2019-06-24 16:58
Could you please attach a self-contained reproducer that can be copy-pasted and run (and fails with CoroutineInternalError)?

**Comment by nbransby** [comment] 2019-06-24 17:02
I can but could do me the honour of giving me your feedback on [#1284](https://github.com/Kotlin/kotlinx.coroutines/issues/1284) first?

**Comment by nbransby** [comment] 2019-06-28 16:49
Spent a while trying to create a self-contained reproducer but cant get it reproducing

**Comment by qwwdfsad** [comment] 2019-07-25 09:21
Closing as "Cannot reproduce" :(

**Closed by qwwdfsad** 2019-07-25 09:21 UTC
Labels: bug, waiting for clarification
