### ISSUE TITLE
Support for Android JetPack

### ISSUE THREAD

**Issue by kptlronyttcna** [Kotlin/kotlinx.coroutines#367] opened 2018-05-23 12:21 UTC
The `kotlinx-coroutines-android` package is not compatible with android JetPack.
See #366 .

**Comment by JakeWharton** [comment] 2018-05-23 15:12
Using the jetifier it works fine. Are you sure you configured it correctly? There should be no work done here until the androidx version of the annotations artifact is stable.

**Comment by kptlronyttcna** [comment] 2018-05-23 16:44
I've created a new application with the empty activity template. Added coroutine dependencies and wrote a simple launch that updated the textview added by the template. Then used the refactor to androidx feature in android studio.

**Comment by choongyouqi** [comment] 2018-06-10 10:09
yup. happened to my project as well. only happen when making the project/apk.
Weird thing is there's no error in the IDE as Android Studio recognize the lib.

Disabling jetifier in gradle.properties works.

**Comment by mateot1** [comment] 2018-08-17 02:10
Also just ran into this. The warning I get is `Type mismatch: inferred type is HandlerContext; but CoroutineContext was expected` and then if I cast `UI` to `CoroutineContext` it becomes `Cannot access class 'Lkotlinx.coroutines.experimental.android.HandlerContext;'. Check your module classpath for missing or conflicting dependencies`.  Unfortunately, I don't think disabling jetifier is an option for me.

**Comment by NamtarR** [comment] 2018-08-20 03:11
Same problem here. Disabling Jetifier would break many other things so it is not an option for me too. The only way I managed to get it to work is copying `kotlinx.coroutines.experimental.android.HandlerContext` and `UI` to my own project. This is obviously not a proper way of fixing this but at least I can continue developing and preparing my app for the future with AndroidX until it all works together without any hacks.

**Comment by pflammertsma** [comment] 2018-08-20 10:10
I can conform that the [workaround offered](https://github.com/Kotlin/kotlinx.coroutines/issues/367#issuecomment-414185769) by @NamtarR works. Be sure to manually correct the support annotations import in UI.kt, otherwise it's as simple as copying that file into your project.

It's an ugly hack, but after spending the whole morning on this, it's the best approach until the problem is resolved upstream.

**Comment by elizarov** [comment] 2018-08-20 10:42
Can you, please, create and publish a small project that would reproduce and demonstrate this problem, so that we can study how to fix (and verify that our fix works).

**Comment by NamtarR** [comment] 2018-08-20 12:09
@elizarov, created [a simple project](https://github.com/NamtarR/CoroutinesTest) that reproduces exactly those errors as stated [here](https://github.com/Kotlin/kotlinx.coroutines/issues/367#issuecomment-413736905). 
```
e: C:\Users\Anton\Documents\Projects\Android\CoroutinesTest\app\src\main\java\com\namtarr\coroutinestest\MainActivity.kt: (15, 16): Cannot access class 'Lkotlinx.coroutines.experimental.android.HandlerContext;'. Check your module classpath for missing or conflicting dependencies
e: C:\Users\Anton\Documents\Projects\Android\CoroutinesTest\app\src\main\java\com\namtarr\coroutinestest\MainActivity.kt: (15, 16): Type mismatch: inferred type is 'HandlerContext'; but CoroutineContext was expected
> Task :app:compileDebugKotlin FAILED
```
It contains one simple `launch` that works perfectly with Jetifier disabled.
Also, it works fine with Jetifier enabled and [this hack](https://github.com/Kotlin/kotlinx.coroutines/issues/367#issuecomment-414185769).

**Comment by abelkov** [comment] 2018-08-22 13:02
Related issue: https://youtrack.jetbrains.com/issue/KT-26224

**Comment by filipedelimabrito** [comment] 2018-08-22 20:08
Facing the same here @elizarov. If you want to see this error in a "real" project, please take a look [here](https://github.com/RocketChat/Rocket.Chat.Android). Thank you.

**Comment by geertberkers** [comment] 2018-08-24 09:20
I can confirm @choongyouqi changing the com.android.tools.build works. Only 3.2.0-beta-05 is currently incompatible and changed to 3.2.0-rc01.

**Comment by guglicap** [comment] 2018-08-25 09:52
I get this if I try to switch to 3.2.0-rc01, though.
Don't know if that's an Android Studio Canary thing.
![image](https://user-images.githubusercontent.com/17258072/44617087-33d7b680-a85d-11e8-8af6-265486fa9537.png)

**Comment by chris118** [comment] 2018-09-07 01:48
@NamtarR it works copy kotlinx.coroutines.experimental.android.HandlerContext to my project

**Comment by donniesky** [comment] 2018-09-07 02:39
@qwwdfsad  Downgrade `com.android.tools.build` to `3.2.0-rc02` works fine too.

**Comment by cckroets** [comment] 2018-10-11 20:49
Now that the `androidx.annotation:annotation:1.0.0` artifact is stable, are there plans to migrate to it?

**Comment by LouisCAD** [comment] 2018-11-28 10:31
@madewulf The kotlinx.coroutines suggested there is outdated (0.26.1). You can use 0.30.2 with Kotlin 1.2 and 1.0+ with Kotlin 1.3+

**Comment by madewulf** [comment] 2018-11-28 10:43
That's what I just found out, thanks!

**Comment by elizarov** [comment] 2019-02-22 14:42
I'm closing this issues as outdated.

**Closed by elizarov** 2019-02-22 14:42 UTC
