### ISSUE TITLE
JUnit tests fail on Android

### ISSUE THREAD

**Issue by deva666** [Kotlin/kotlinx.coroutines#680] opened 2018-10-08 11:34 UTC
I have an Android library where I have some parts of the code that I can unit test without an Android device. 
Upgrading the coroutines from v.0.22 to 0.30.1 introduced the `Dispatchers` object and deprecated the `UI` Android Context.
Now my unit tests fail with the following errors.

```
java.lang.ExceptionInInitializerError
	at kotlinx.coroutines.experimental.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:43)
	at kotlinx.coroutines.experimental.Dispatchers.loadMainDispatcher(Dispatchers.kt:29)
	at kotlinx.coroutines.experimental.Dispatchers.<clinit>(Dispatchers.kt:24)
	at kotlinx.coroutines.experimental.CoroutineContextKt.newCoroutineContext(CoroutineContext.kt:83)
	at kotlinx.coroutines.experimental.BuildersKt__Builders_commonKt.launch(Builders.common.kt:49)
	at kotlinx.coroutines.experimental.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:46)
	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Unknown Source)
```

and

```
java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.experimental.Dispatchers

	at kotlinx.coroutines.experimental.CoroutineContextKt.newCoroutineContext(CoroutineContext.kt:83)
	at kotlinx.coroutines.experimental.BuildersKt__Builders_commonKt.launch(Builders.common.kt:49)
	at kotlinx.coroutines.experimental.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:46)
	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Unknown Source)
```

I only took a quick look at the `Dispatchers` code. Seems like a static initializer fires for this object and calls the `loadMainDispatcher` function, which finds my `kotlinx-coroutines-android` module in the classpath and loads the Android `Dispatchers.Main`.
This one of course requires Android specific code, which I don't have in my unit tests.

**Comment by elizarov** [comment] 2018-10-08 12:35
This is a duplicate of #658. Will be fixed in the upcoming patch.

**Closed by elizarov** 2018-10-08 12:35 UTC
