### ISSUE TITLE
1.5.0 withContext() method has an ANR issues

### ISSUE THREAD

**Issue by gittosuperfly** [Kotlin/kotlinx.coroutines#3429] opened 2022-08-29 06:58 UTC
**version :** org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.0
**my code:**
```Kotlin
object LocalFileLoader {

    private val coroutineScope: CoroutineScope by lazy {
        CoroutineScope(Job() + Dispatchers.Main)
    }

    // The Job being downloading will be put into this one Map, It will be removed after the download is completed.
    private val downloadingMap = ConcurrentHashMap<String, Job>()

    @JvmStatic
    fun loadLocalFile(
        localId: String,
        waitDownload: Boolean = true,
        callback: (Map<String, ByteArray>?) -> Unit
    ) {
        coroutineScope.launch {
            val result = loadLocalFile(localId, waitDownload)
            callback(result)
        }
    }

    suspend fun loadLocalFile(
        localId: String,
        waitDownload: Boolean = true
    ): Map<String, ByteArray>? {
        return withContext(Dispatchers.IO) {
            if (waitDownload) {
                downloadingMap[localId]?.join()
            }
            getLocal(localId)?.let {
                return@withContext it.content
            }
            return@withContext null
        }
    }
    
    fun getLocal(localId: String) = ... //load data from local cache
}
```

**Google Play ANR details message**
**Incidence rate**: ~ 0.1%
**Front and back stage**: all background
**android version**: all
**some log:**
```
at kotlin.internal.PlatformImplementations.defaultPlatformRandom (PlatformImplementations.java:45)
at kotlin.random.Random.<clinit> (Random.java:271)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:638)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:593)
at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker (CoroutineScheduler.java:482)
at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker (CoroutineScheduler.java:440)
at kotlinx.coroutines.scheduling.CoroutineScheduler.signalBlockingWork (CoroutineScheduler.java:421)
at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.java:402)
at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (ExperimentalCoroutineDispatcher.java:115)
at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:170)
at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:160)
at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuationKt.java:332)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (CancellableKt.java:30)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (CancellableKt.java:25)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:170)
at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
......
loadLocalFile()
My business code calls
......
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
at android.os.Handler.handleCallback (Handler.java:873)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loop (Looper.java:233)
at android.app.ActivityThread.main (ActivityThread.java:7225)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:962)
```
Another log：
```
  #00  pc 0x000000000001b9a8  /system/lib64/libc.so (__bionic_clone)
  #00  pc 0x000000000001dcf4  /system/lib64/libc.so (clone)
  #00  pc 0x000000000006a22c  /system/lib64/libc.so (pthread_create)
  #00  pc 0x000000000044d33c  /system/lib64/libart.so (art::Thread::CreateNativeThread(_JNIEnv*, _jobject*, unsigned long, bool))
  #00  pc 0x00000000000bb0f8  /system/framework/arm64/boot.oat (Java_java_lang_Thread_nativeCreate__Ljava_lang_Thread_2JZ)
  at java.lang.Thread.nativeCreate (Thread.java)
  at java.lang.Thread.start (Thread.java:730)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker (CoroutineScheduler.java:485)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker (CoroutineScheduler.java:440)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.signalBlockingWork (CoroutineScheduler.java:421)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.java:402)
  at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (ExperimentalCoroutineDispatcher.java:115)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:170)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:160)
  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuationKt.java:332)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (CancellableKt.java:30)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (CancellableKt.java:25)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:170)
  at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
......
loadLocalFile()
My business code calls
......
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6328)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1076)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:937)
```

**Comment by qwwdfsad** [comment] 2022-08-29 10:27
It seems like the checker is too sensitive -- the second stacktrace is a regular thread creating that happens here and there all the time. Probably, on slow and old devices it can be interpreted as ANR.

The first one is a bit trickier, as it is hard to tell what exactly this stacktrace is referring to -- likely reflection-based instantiation of `PlatformImplementations`, but it should not cause ANR as well.

For now, I'll close this as "won't fix, there is nothing to do", but if we see more reports about `PlatformImplementations`, we'll see how we can rewrite it to be more reflection-friendly

**Closed by qwwdfsad** 2022-08-29 10:27 UTC
Labels: android

**Comment by gittosuperfly** [comment] 2022-08-29 10:46
@qwwdfsad   More log case : 

case:
```
  at kotlinx.coroutines.internal.LockFreeTaskQueueCore.addLast (LockFreeTaskQueueCore.java:320)
  at kotlinx.coroutines.internal.LockFreeTaskQueue.addLast (LockFreeTaskQueue.java:48)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.addToGlobalQueue (CoroutineScheduler.java:120)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.java:390)
  at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (ExperimentalCoroutineDispatcher.java:115)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:170)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:160)
  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuationKt.java:332)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (CancellableKt.java:30)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (CancellableKt.java:25)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:170)
  at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
  ......
  ......
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7817)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1027)
```

case:
```
  at kotlinx.coroutines.JobKt__JobKt.ensureActive (JobKt__JobKt.java:601)
  at kotlinx.coroutines.JobKt.ensureActive (JobKt.java:1)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:153)
  at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
  ......
  ......
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
  at android.os.Handler.handleCallback (Handler.java:899)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:238)
  at android.app.ActivityThread.main (ActivityThread.java:7853)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:984)
```

case:
```
  at kotlinx.coroutines.scheduling.CoroutineScheduler$WorkerState.<clinit> (CoroutineScheduler.java:943)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:608)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:593)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker (CoroutineScheduler.java:482)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker (CoroutineScheduler.java:440)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.signalBlockingWork (CoroutineScheduler.java:421)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.java:402)
  at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (ExperimentalCoroutineDispatcher.java:115)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:170)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:160)
  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuationKt.java:332)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (CancellableKt.java:30)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (CancellableKt.java:25)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:170)
  at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
  ......
  ......
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:257)
  at android.app.ActivityThread.main (ActivityThread.java:8192)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:626)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1015)
```

case:
```
  at kotlin.random.Random.<clinit> (Random.java:271)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:638)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.<init> (CoroutineScheduler.java:593)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.createNewWorker (CoroutineScheduler.java:482)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.tryCreateWorker (CoroutineScheduler.java:440)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.signalBlockingWork (CoroutineScheduler.java:421)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.java:402)
  at kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (ExperimentalCoroutineDispatcher.java:115)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:170)
  at kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (LimitingDispatcher.java:160)
  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuationKt.java:332)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (CancellableKt.java:30)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (CancellableKt.java:25)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (BuildersKt__Builders_commonKt.java:170)
  at kotlinx.coroutines.BuildersKt.withContext (BuildersKt.java:1)
  ......
  ......
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7405)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:502)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

**Comment by qwwdfsad** [comment] 2022-08-29 10:49
Thanks! 

This indeed seems to be spurious failures: neither `addLast` nor `ensureActive ` do anything CPU-intensive and/or potentially blocking. I suggest reporting these to Google with specific vendor details of devices where such ANRs are reproducible
