### ISSUE TITLE
Launch inside callback of of AlertDialog not executing code

### ISSUE THREAD

**Issue by SaschaZ** [Kotlin/kotlinx.coroutines#936] opened 2019-01-15 16:45 UTC
When i place a `launch` statement inside the callback of an `AlertDialog` the code does not get executed. Calling the `launch` on `GlobalScope` fixes it.

```kotlin
import android.os.Bundle
import android.util.Log
import android.view.ViewGroup.LayoutParams.MATCH_PARENT
import android.widget.Button
import android.widget.FrameLayout
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

class MainActivity : AppCompatActivity() {

    companion object {

        private val TAG = MainActivity::class.java.simpleName
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(FrameLayout(this).also { it.addView(Button(this).apply {
            text = "ask me"
            setOnClickListener { onButtonClicked() }
        })}, FrameLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT))
    }

    private fun onButtonClicked() = GlobalScope.launch(Dispatchers.Main) {
        AlertDialog.Builder(this@MainActivity).setMessage("Do it?").setPositiveButton("Yes") { _, _ ->
            Log.w(TAG, "answered yes")
            launch {
                Log.w(TAG, "inside launch without GlobalScope") // this does not get executed
            }
            GlobalScope.launch {
                Log.w(TAG, "inside launch with GlobalScope")
            }
        }.setNegativeButton("No") { _, _ ->}.show()
    }
}

```

**Comment by AllanWang** [comment] 2019-01-15 17:57
This is because your inner `launch` is executed within the job of your parent `launch`. As the parent finishes once the dialog is created, all children are cancelled.

Using global scope again avoids that hierarchy, so they are independent

**Comment by SaschaZ** [comment] 2019-01-15 20:36
Ok. Makes sense. But this is also not working:
```kotlin
class MainActivity : AppCompatActivity(), CoroutineScope {

    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Default
...

    private fun onButtonClicked() = GlobalScope.launch(Dispatchers.Main) {
        AlertDialog.Builder(this@MainActivity).setMessage("Do it?").setPositiveButton("Yes") { _, _ ->
            Log.w(TAG, "answered yes")
            launch {
                Log.w(TAG, "inside launch wo GlobalScope") // this is not called
            }
            GlobalScope.launch {
                Log.w(TAG, "inside launch with GlobalScope")
            }
        }.setNegativeButton("No") { _, _ ->}.show()
    }
}
````

This should work because the class implements a `CoroutneScope` right?

**Comment by AllanWang** [comment] 2019-01-15 20:52
The launch block is of type `CoroutineScope.() -> Unit` or something. You have to use `this@MainActivity` to actually use the activity scope

**Comment by SaschaZ** [comment] 2019-01-15 20:55
Ah. Now it makes sense. Thank you very much!

But i think this should throw a compile error, like other similar cases.

**Comment by AllanWang** [comment] 2019-01-15 20:59
It's not that you can't launch child blocks within another coroutine scope. The problem here is that you are launching it from a separate callback (once the positive button is pressed), which doesn't register before the parent launch finishes. You won't have this problem without such callbacks, and the coroutine way of doing this would be to make the callbacks suspend functions

**Comment by SaschaZ** [comment] 2019-01-15 21:33
Than maybe a warning at runtime? The problem for me is that there is nothing that tells me that my launched coroutine is not executed at all. Are there any cases where this is intended?

**Comment by AllanWang** [comment] 2019-01-15 21:39
How would you warn about this at runtime? The failure is caused because the second child is not launched at all.

If you had 

```
launch {
    launch {
   }
}
```

or 

```
launch {
    suspendFun()
    launch {
    }
}
```

they would all work, as the child launch is created before the parent stops.

For debugging purposes, if you really want to know if a launch executes, you can add some logging function at the start.

The general idea is that if a parent is cancelled, all child requests will not execute. In your case the parent has stopped before your child request, and it therefore no longer runs, which is intended behaviour.


You can draw a similar analogy with view building. Say you are inside a view, and you have another function that takes in `View.() -> Unit`. You want to update the text of your current view, rather than your builder's view, but both are in the `View` scope. It is therefore your responsibility now to specify which view you are referring to when updating the text.

**Comment by AllanWang** [comment] 2019-01-15 21:42
Another way you can write this, which I haven't verified, is to define you child launch behaviour before creating the dialog. It will return the job, and when creating the launch, you can specify a lazy start.
You can then create your dialog and, in your positive button listener, start the job. This is a bit more explicit

**Comment by elizarov** [comment] 2019-02-22 14:34
I'm closing this, because this behavior is as designed.

**Closed by elizarov** 2019-02-22 14:34 UTC

**Comment by mtangoo** [comment] 2020-05-22 16:31
for completion just use lifecycleScope as launcher and it will work fine!

```
        AlertDialog.Builder(this@MainActivity).setMessage("Do it?").setPositiveButton("Yes") { _, _ ->
            Log.w(TAG, "answered yes")
            lifecycleScope.launch {
                Log.w(TAG, "inside launch with lifecycleScope") 
            }
        }.show()
```
