### ISSUE TITLE
[Enhancement]  add `CoroutineScope.asScheduler` and  `CoroutineDispatcher.asScheduler` to kotlinx-coroutines-rx2

### ISSUE THREAD

**Issue by Guang1234567** [Kotlin/kotlinx.coroutines#1024] opened 2019-03-03 16:03 UTC
Hello dev:

Could you add `CoroutineScope.asScheduler` and  `CoroutineDispatcher.asScheduler` function that
let using coroutine in rxjava is possible.  Thx.

>[kotlinx-coroutines-rx2](https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2) is only support using rxjava in coroutine now.

**Comment by JakeWharton** [comment] 2019-03-03 16:05
Dupe of #968?

**Comment by Guang1234567** [comment] 2019-03-04 02:26
@JakeWharton 

Yes, #968 already has a demo that implement `CoroutineDispatcher.asScheduler`, nice!

but `CoroutineScope.asScheduler` ?

**Comment by qwwdfsad** [comment] 2019-03-04 08:34
>CoroutineScope.asScheduler

Do you mean just a shorthand for extracting dispatcher from a scope and calling `asScheduler` or a more complex semantics?

**Comment by Guang1234567** [comment] 2019-03-04 09:22
@qwwdfsad 
more complex semantics.  see #968

**Comment by qwwdfsad** [comment] 2019-03-04 11:21
Ok, let's keep track there, will close this as duplicate

**Closed by qwwdfsad** 2019-03-04 11:21 UTC
