### ISSUE TITLE
AccessControlException running embedded code in "Coroutine context and dispatchers﻿: Jumping between threads﻿" documentation

### ISSUE THREAD

**Issue by ikolomiets** [Kotlin/kotlinx.coroutines#2556] opened 2021-02-26 02:32 UTC

**Comment by ikolomiets** [comment] 2021-02-26 02:33
Here https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#jumping-between-threads
<img width="631" alt="Screen Shot 2021-02-25 at 21 31 48" src="https://user-images.githubusercontent.com/631003/109246898-0b73fe80-77b1-11eb-9ef7-ec41287743de.png">

**Comment by qwwdfsad** [comment] 2021-03-01 15:13
Thanks!

It is a duplicate of #2166

**Closed by qwwdfsad** 2021-03-01 15:13 UTC
