### ISSUE TITLE
Broken documentation about `runTest` in `kotlinx-coroutines-test` main page

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/kotlinx.coroutines#3177] opened 2022-02-08 14:07 UTC
Here is what the docs look like at the bottom of [this page](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/):
![image](https://user-images.githubusercontent.com/1913296/153003076-bf086106-56d3-4053-a772-6599c4b23b50.png)

**Comment by dkhalanskyjb** [comment] 2022-02-09 09:29
Hilarious! Also, the problem is more pronounced than that: in fact, most of the https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-test page is absent.

**Comment by joffrey-bion** [comment] 2022-02-09 10:15
Yeah I noticed it after checking the README, the rest of the page was also dropped 😄

**Comment by hfhbd** [comment] 2022-02-14 11:26
I think this is the cause https://github.com/Kotlin/dokka/issues/1838

**Comment by IgnatBeresnev** [comment] 2022-04-15 18:44
JFYI this has been fixed in Dokka 1.6.20, I can send a PR your way if you want :)

**Closed** 2022-04-26 11:53 UTC
Labels: docs
