### ISSUE TITLE
Running latest coroutines with latest kotlin 1.3.30 causes iOS build issues

### ISSUE THREAD

**Issue by Syrou** [Kotlin/kotlinx.coroutines#1099] opened 2019-04-15 12:02 UTC
Before upgrading to latest coroutines I used `1.2.0-alpha` and kotlin version: 1.3.20
everything was successfully able to compile

Now, using the following new dependency setup:
```
# kotlin
kotlin_version=1.3.30
kotlin.code.style=official
kotlin.experimental=true
kotlin.incremental.multiplatform=true

# Project dependencies
coroutines_version=1.2.0
serialization_version=0.11.0
kotlinx_io_version=0.1.3
ktor_version=1.2.0-alpha-1.3.0-eap-125
```

Dependencies for iOS are now:
```
      iOSMain {
            dependencies {
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutines_version"
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"

                implementation "io.ktor:ktor-client-ios:$ktor_version"
                implementation "io.ktor:ktor-client-core-native:$ktor_version"
                implementation "io.ktor:ktor-client-json-native:$ktor_version"
                implementation "io.ktor:ktor-client-logging-native:$ktor_version"
            }
        }
```

When trying to build I now get:
```
> Task :SharedCode:linkMainDebugFrameworkIOS FAILED
e: Compilation failed: Could not find "kotlinx-coroutines-core-native" in [/Users/user/Source/multiplatform-sdk/SharedCode, /Users/user/.konan/klib, /Users/user/.konan/kotlin-native-macos-1.2/klib/common, /Users/user/.konan/kotlin-native-macos-1.2/klib/platform/ios_arm64].

 * Source files: /*OMITTED*/
 * Compiler version info: Konan: 1.2 / Kotlin: 1.3.30
 * Output kind: FRAMEWORK

e: java.lang.IllegalStateException: Could not find "kotlinx-coroutines-core-native" in [/Users/user/Source/multiplatform-sdk/SharedCode, /Users/user/.konan/klib, /Users/user/.konan/kotlin-native-macos-1.2/klib/common, /Users/user/.konan/kotlin-native-macos-1.2/klib/platform/ios_arm64].
	at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver.resolve(SearchPathResolver.kt:194)
	at org.jetbrains.kotlin.konan.library.SearchPathResolver$DefaultImpls.resolve$default(SearchPathResolver.kt:18)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$resolveDependencies$$inlined$map$lambda$1.invoke(KonanLibraryResolverImpl.kt:96)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$resolveDependencies$$inlined$map$lambda$1.invoke(KonanLibraryResolverImpl.kt:24)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:732)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:723)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.resolveDependencies(KonanLibraryResolverImpl.kt:109)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.resolveWithDependencies(KonanLibraryResolverImpl.kt:34)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:99)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.getResolvedLibraries$backend_native_compiler(KonanConfig.kt)
	at org.jetbrains.kotlin.backend.konan.TopDownAnalyzerFacadeForKonan.analyzeFiles(TopDownAnalyzerFacadeForKonan.kt:43)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1$1.invoke(ToplevelPhases.kt:41)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1$1.invoke(ToplevelPhases.kt)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1.invoke(ToplevelPhases.kt:40)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1.invoke(ToplevelPhases.kt)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

If I were to revert `coroutines_version=1.2.0` to `coroutines_version=1.1.1-eap13-125` or simply remove the `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutines_version"` line
this error instead becomes:
```
> Task :SharedCode:linkMainDebugFrameworkIOS
e: Compilation failed: findDeserializedDeclaration: symbol org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterSymbolImpl@5da0e938 is unbound, descriptor = K, hash = 307996568

 * Source files: /* OMITTED */
 * Compiler version info: Konan: 1.2 / Kotlin: 1.3.30
 * Output kind: FRAMEWORK

e: java.lang.AssertionError: findDeserializedDeclaration: symbol org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterSymbolImpl@5da0e938 is unbound, descriptor = K, hash = 307996568
	at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclaration(KotlinIrLinker.kt:365)
	at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateOrGetTypeParameterStub$1.invoke(DeclarationStubGenerator.kt:220)
	at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateOrGetTypeParameterStub$1.invoke(DeclarationStubGenerator.kt:35)
	at org.jetbrains.kotlin.ir.util.SymbolTable.declareGlobalTypeParameter(SymbolTable.kt:671)
	at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.generateOrGetTypeParameterStub$ir_tree(DeclarationStubGenerator.kt:219)
	at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator$DependencyGenerationTask.run(ExternalDependenciesGenerator.kt:59)
	at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:36)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:48)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:61)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:98)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by qwwdfsad** [comment] 2019-04-15 18:42
It looks like the problem with migration to new mpp model.
Could you please check whether this problem is reproducible with coroutines `1.2.0`, Ktor `1.1.4` and Kotlin `1.3.30`?

**Comment by Syrou** [comment] 2019-04-16 07:29
@qwwdfsad Can confirm that the ` java.lang.AssertionError: findDeserializedDeclaration: symbol org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterSymbolImpl@258a435c is unbound, descriptor = K, hash = 1191732945`

Happens if i run those versions

**Comment by Syrou** [comment] 2019-04-16 09:19
I recreated this issue with a barebone project, and this specific part seems to be the culprit, which means this is probably related to Serialization rather than coroutines:
```
import kotlinx.serialization.Serializable
import kotlinx.serialization.internal.HashMapSerializer

@Serializable
class SendAchievementGig(
    val dataAsJson: String,
    @Serializable(HashMapSerializer::class) val options: HashMap<String, String> = hashMapOf()
)
```

**Comment by qwwdfsad** [comment] 2019-04-16 09:26
Thanks, it indeed may be the issue with serialization, we will investigate further.
Could you please attach your project with a reproducer?

**Comment by Syrou** [comment] 2019-04-16 09:36
@qwwdfsad https://github.com/Syrou/KotlinSerializationBugRepro

**Comment by qwwdfsad** [comment] 2019-04-17 14:35
It appears to be a bug in the serialization plugin, so closing this one

**Closed by qwwdfsad** 2019-04-17 14:35 UTC
Labels: question
