### ISSUE TITLE
WeakJob

### ISSUE THREAD

**Issue by InsanusMokrassar** [Kotlin/kotlinx.coroutines#2626] opened 2021-04-05 09:01 UTC
I have a feature request about `WeakJob`s. Currently in my practice there are tasks (`Job`) which are not important in context of `CoroutinesScope` and can be (sometimes `must` be) cancelled when there are no any strong `Job` (common `Job`) left in this `CoroutineScope`. As I remember, currently when we are calling `launch`/`async` methods on `CoroutineScope` we will get  new `Job` and this `Job` will prohibit `CoroutineScope` to be completed until `Job` will not be completed too.

## Example of syntax

```kotlin
val scope = CoroutineScope(Dispatchers.Default)
scope.weakLaunch {
    while (isActive) {
        println("still working")
    }
}
scope.launch {
    delay(5100L)
    println("that will be last one")
}
```

It is expected that the code above will print:

```bash
still working
still working
still working
still working
still working
that will be last one
```

**Comment by InsanusMokrassar** [comment] 2021-04-05 09:09
Currently there is way to get the same functionality (as I understand):

```kotlin
val scope = CoroutineScope(Dispatchers.Default)
val subScope = CoroutineScope(scope.coroutineContext)
scope.coroutineContext.job.invokeOnCompletion { subScope.cancel() }

subScope.launch {
    while (isActive) {
        println("still working")
    }
}
scope.launch {
    delay(5100L)
    println("that will be last one")
}
```

**Comment by MairwunNx** [comment] 2021-04-05 09:49
The name `weak` slightly violates the principle of naming objects that are weak to the garbage collector. Maybe you should choose a different name for such a function?

**Comment by InsanusMokrassar** [comment] 2021-04-05 10:13
> The name `weak` slightly violates the principle of naming objects that are weak to the garbage collector. Maybe you should choose a different name for such a function?

I have chosen this name exactly because in context of scopes closing that will means, that this scope is not direct child and should not be counted as subscope

**Comment by fvasco** [comment] 2021-04-05 18:48
I wrote something similar here: #1065

**Comment by elizarov** [comment] 2021-04-06 07:19
@fvasco Thanks for the link. Yes, this request is essentially a duplicate of #1065

**Closed by elizarov** 2021-04-06 07:19 UTC
