### ISSUE TITLE
Feature request: allow stacktrace recovery in production

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/kotlinx.coroutines#3611] opened 2023-01-31 19:54 UTC
**Use case**

I know we could do a round-about way via excluding the embedded proguard rules that come with coroutines, but that’s fairly cumbersome and I wonder if this could be done a separate way. The reason I ask is because we want traces from production and our bug reporting tool can retrace these (we do the same with RxDogTag, of which I’m the author). This has been immensely beneficial to us in tracking and fixing bugs that happen in production, as otherwise the stacktraces sent back are unustable.

I recognize this comes at a performance cost and understand why coroutines defaults to not allowing this with its proguard rules, but it is also currently making this decision for consumers and I think it would be valuable to be able to enable it.

**The Shape of the API**

I don't have a clear idea of how it would work with coroutines, but in RxDogTag we basically gate installation/init of its capturing behavior via global boolean flag and don't automatically remove its machinery via embedded proguard rules.

**Prior Art**

https://github.com/uber/rxdogtag

**Comment by dkhalanskyjb** [comment] 2023-05-03 09:33
Duplicate of #1998.

**Closed by dkhalanskyjb** 2023-05-03 09:33 UTC
Labels: enhancement, debug
