### ISSUE TITLE
0.14 not in jcenter

### ISSUE THREAD

**Issue by jsullivanch** [Kotlin/kotlinx.coroutines#43] opened 2017-03-22 20:21 UTC
I'm sorry if this is a bintray issue and doesn't belong here, but the 0.14 jar (which is referenced in the README) doesn't exist on bintray.

It shows up in search, here: https://bintray.com/kotlin/kotlinx/kotlinx.coroutines

However, the files are missing: https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/

If you attempt to add 0.14 (or 0.14.1, which also shows up in search) gradle produces:
```
* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find org.jetbrains.kotlinx:kotlinx-coroutines-core:0.14.1.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.14.1/kotlinx-coroutines-core-0.14.1.pom
      https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.14.1/kotlinx-coroutines-core-0.14.1.jar
      https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.14.1/kotlinx-coroutines-core-0.14.1.pom
      https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.14.1/kotlinx-coroutines-core-0.14.1.jar
  Required by:
      project :
```

I managed to receive a jar by changing my version to `0.13`

It might be worth noting that `kotlinx-coroutines` has a pom file, but no jar:
https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines/0.14.1/

**Comment by ilya-g** [comment] 2017-03-23 04:16
There's a problems with jcenter sync of the coroutines package. We're trying to get in contact with bintray support on this.
You can use the primary bintray repository where the package is published as a workaround: http://kotlin.bintray.com/kotlinx

**Comment by ilya-g** [comment] 2017-03-26 21:39
The problem is fixed now, the packages are available on jcenter again.

**Closed by ilya-g** 2017-03-26 21:39 UTC
