### ISSUE TITLE
iOS app doesn't crash when throw exception in CoroutineScope with Dispatchers.Default

### ISSUE THREAD

**Issue by belousovgm** [Kotlin/kotlinx.coroutines#2723] opened 2021-05-21 10:57 UTC
Hi!
Why code like this:
```
CoroutineScope(Dispatchers.Default).launch {
throw IllegalStateException()
}
```
doesn't crash iOS app?

But 
```
CoroutineScope(Dispatcher.Main).launch {
    withContext(Dispatcher.Default) {
        throw IllegalStateException()
    }
}
```
crashes.

Kotlin: 1.4.31
Coroutines: 1.4.2-native-mt

**Comment by Thomas-Vos** [comment] 2021-05-24 10:50
See the following: https://github.com/Kotlin/kotlinx.coroutines/issues/2398

**Comment by qwwdfsad** [comment] 2021-07-12 14:51
Fixed in `1.5.1-native-mt`. For an additional explanation of the behaviour see https://github.com/Kotlin/kotlinx.coroutines/pull/2804#discussion_r667930024

**Closed by qwwdfsad** 2021-07-12 14:51 UTC
Labels: bug, native

**Comment by YoussefHachicha** [comment] 2024-04-29 14:24
if fixed in 1.5.1-native-mt should it not happen in 1.8.0? because the issue is happening to me in 1.8.0 ??
