### ISSUE TITLE
StateFlow .combine usage with .asLiveData

### ISSUE THREAD

**Issue by carterhudson** [Kotlin/kotlinx.coroutines#2411] opened 2020-11-26 01:46 UTC
I'm using `StateFlow` under the hood, but still exposing `LiveData` in my API. I'm currently experiencing some unexpected behavior with regard to calling `combine` to join two instances of `MutableStateFlow`, and subsequently using the combined value as `LiveData`.

```kotlin
    private val _read = MutableStateFlow<ChannelUserRead?>(null)
    private val _messages = MutableStateFlow<Map<String, Message>>(emptyMap())

    ...

    private val _unreadCount: StateFlow<Int?> =
        _read.combine(_messages) { channelUserRead: ChannelUserRead?, messagesMap: Map<String, Message> ->
            computeUnreadCount(domainImpl.currentUser, channelUserRead, messagesMap.values.toList())
        }.stateIn(domainImpl.scope, SharingStarted.Eagerly, 0)

    override val unreadCount: LiveData<Int?> = _unreadCount.asLiveData()
```

I would expect this to run the combine transformation any time `_read` or `_messages` value changes, and also notify any observers of the `unreadCount`. This seems to work in the acutal app, but previously passing tests now fail when trying to validate `unreadCount.value`. It seems that, when under test, the combine transformation is called once on instantiation, and not when `_messages.value` is updated, and so
```kotlin
            channelController.unreadCount.getOrAwaitValue().let { unreadCount ->
                Truth.assertThat(unreadCount).isEqualTo(1)
            }
```
always fails with actual being 0.

**Comment by elizarov** [comment] 2020-11-26 14:26
Do you see the problem only in the resulting `LiveData` (`unreadCount`). Does `StateFlow` (`_unreadCount`) work properly? If so, then I'd suspect there is some problem with `asLiveData` implementation. Any chance you can provide a small project with a self-cotainted reproducer/test to figure it out?

**Comment by carterhudson** [comment] 2020-11-26 19:10
It's strange. `_unreadCount` seems to work when running the actual app, but not when under test. Since `_read` + `_messages` = `_unreadCount`, updating `_messages.value` triggers the transformation function specified for `.combine()`, and `_unreadCount` gets updated, but not when running unit tests. The `LiveData` `unreadCount`, however, doesn't seem to work when running the app, or under test. I'll try to reproduce it in a sample app and post it here. Might take me a bit because of the Thanksgiving holiday.

**Comment by vitorhugods** [comment] 2020-11-27 20:21
I'm facing a similar issue...

```
class MyViewModel {
    private val stateFlow = MutableStateFlow(initialState)
    val state = stateFlow.asLiveData()
}
```

As soon as I get an instance of `MyViewModel` and attempt to observer `state`, the `initialState` is there.

But when doing the same during tests (instantiating a ViewModel and attempt to observe the LiveData), it's `null`.

**Comment by carterhudson** [comment] 2020-11-28 00:22
@elizarov Here's a [project](https://github.com/carterhudson/2411) I made that is configured as closely as I can get for now. Check out the test to see something similar to what I am encountering (combine runs once, but never again / late).

**Comment by carterhudson** [comment] 2020-11-30 19:05
I tried using a `MediatorLiveData` instead to see if I could get it to trigger, but also had no luck. Should I expect 
```kotlin
    private val _read = MutableStateFlow<ChannelUserRead?>(null)
    private val _messages = MutableStateFlow<Map<String, Message>>(emptyMap())

    override val unreadCount: LiveData<Int?> = MediatorLiveData<Int?>().apply {
        addSource(_read.asLiveData()) { read ->
            read?.user?.let { user -> computeUnreadCount(user, read, _messages.value.values.toList()) }
        }

        addSource(_messages.asLiveData()) { messageMap ->
            _read.value?.let { read -> computeUnreadCount(read.user, read, messageMap.values.toList()) }
        }

        value = 0
    }
```
to behave similarly to `.combine(...)`? The `onChanged` observers are never triggered 🤔

**Comment by carterhudson** [comment] 2020-12-01 16:47
@elizarov My coworker made a simplified project that doesn't use Robolectric and the problem still persists, but he managed to get the tests to work properly by calling `yield()` or `delay(1)` anywhere in the test. https://github.com/zsmb13/2411

**Comment by elizarov** [comment] 2020-12-02 15:02
@carterhudson Data updates in flows are _asynchronous_. So in your test code when you call `controller.incrementA()` the update does not get immediately propagated to all the downstream flows, but is scheduled for update in the future. In you test code you can call `advanceUntilIdle()` immediately after this call and before reading the result of the combined flow and the test will consistently pass, because `advanceUntilIdle()` makes sure that all those asynchronous actions finish their execution.

P.S. That fact that it passes with `delay(1)` in the beginning is run a coincidence in this particular case.

**Comment by carterhudson** [comment] 2020-12-02 19:28
For some reason, it seems as if I can call `advanceUntilIdle()` as the very first line of my `runBlockingTest { ... }` and they execute as expected. Is that expected behavior?

**Comment by elizarov** [comment] 2020-12-03 07:38
It is not expected, but it may, indeed, change the behavior, just like putting `delay` makes it work in this particular test case. This is definitely not a general solution and does not guarantee anything if you write a longer test. Data propagation through a flow is, in general, asynchronous. On the other hand, putting `advanceUntilIdle()` _after_ updates guarantees that all data propagation had finished and you can safely assert the derived values.

**Comment by zsmb13** [comment] 2020-12-03 14:41
Makes sense, thanks for the explanations! I think we can close this 😄

**Closed** 2020-12-04 12:27 UTC
Labels: android
