### ISSUE TITLE
Using TestScope.advanceUntilIdle() breaks suspendCancellableCoroutine

### ISSUE THREAD

**Issue by jeffdgr8** [Kotlin/kotlinx.coroutines#3819] opened 2023-07-20 19:00 UTC
**Describe the bug**

When migrating some code in my library to convert a callback API to a suspend function with `suspendCancellableCoroutine`, I found the `CancellableContinuation` was already canceled and couldn't be resumed with the callback result. I traced this to using `TestScope.advanceUntilIdle()` in the tests exercising the code. Once I removed this and replaced with a `delay()` instead, the `suspendCancellableCoroutine` behaved as expected, where `CancellableContinuation` could be resumed.

[Original Slack thread](https://kotlinlang.slack.com/archives/C1CFAFJSK/p1688755224306679?thread_ts=1688632271.037179&cid=C1CFAFJSK)

**Provide a Reproducer**

I'll be releasing my library soon and can share a reproducer at that time. Creating the issue now so I don't forget.

**Comment by dkhalanskyjb** [comment] 2023-07-24 06:30
Though it is impossible to say for sure without a reproducer, it's very likely that there is no problem on our side and your code is just flaky. `advanceUntilIdle` only works on CoroutineDispatcher instances that were mocked with test ones, so if you have something like `appScooe.launch(Dispatchers.Default)`, don't mock `Dispatchers.Default`, and don't wait for the result in any way, then `advanceUntilIdle` may finish earlier than the forked-off task does. This is not a bug but a feature: if my assumption is true, then you have a race condition, and the failing test is an indicator of that.

If you do end up finding a reproducer, please share it, but until then, I'm closing the issue, as without a reproducer, it doesn't give us anything actionable.

**Closed** 2023-07-24 06:31 UTC
Labels: bug, test

**Comment by jeffdgr8** [comment] 2023-07-24 15:48
@dkhalanskyjb Having this issue open was my reminder to share a reproducer. I can describe the code in the meantime.

The code is based on the SQLDelight paging extension. `TestScope.advanceUntilIdle()` is called [here](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/WithPagingDataDiffer.kt#L51). `suspendCancellableCoroutine ` is introduced [here](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSource.kt#L61) with a callback API returning the query results.

[Tests that call `withPagingDataDiffer`](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt#L94) fail because `suspendCancellableCoroutine`'s continuation is in the canceled state when the callback occurs.

I'm only using the `runTest` `TestScope` with `EmptyCoroutineContext`, no other dispatcher. Is the problem that `advanceUntilIdle` is advancing to when `suspendCancellableCoroutine` suspends and then fails the test, which cancels the `runtTest` coroutine?

I wish there was a better mechanism to wait for the [`load()` suspend function](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSource.kt#L43-L76) to complete, as currently my test code relies on an arbitrary `delay`, replacing the previously used `advanceUntilIdle`. If the above is accurate, seems I may need something like `advanceUntilIdle`, `advanceUntilRunning` (which doesn't exist?), and `advanceUntilIdle` again.

**Comment by jeffdgr8** [comment] 2023-07-25 23:35
The coroutine is canceled with `job.cancel()` because it will [continue to collect](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/androidx/paging/AsyncPagingDataDiffer.kt#L132-L133) until the `PagingData` is invalidated. The test is just testing the result of the first `PagingSource.load()` execution. Also, the test is failing on [the line above](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/WithPagingDataDiffer.kt#L52) before it actually cancels the coroutine.

I am finding the problem seems to be that `advanceUntilIdle()` returns and `block(pagingDataDiffer)` executes its checks before the async callback is able to resume the continuation. The callback does happen before the test actually completes though, maybe because `runTest` is waiting for its child coroutines to complete? The continuation is cancelled, I guess from the exception thrown in the failed assertion in `block`, and it's unable to resume it.

**Comment by dkhalanskyjb** [comment] 2023-07-26 06:07
> I am finding the problem seems to be that advanceUntilIdle() returns and block(pagingDataDiffer) executes its checks before the async callback is able to resume the continuation.

Yes, and this can only happen if the callback happens outside the test dispatcher, in which case `advanceUntilIdle` simply can't do anything.

**Comment by jeffdgr8** [comment] 2023-07-26 17:50
I tried using [`TestScope.coroutineContext` instead of `EmptyCoroutineContext`](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt#L383), but this didn't help and broke other tests for different reasons (because the scope is cancelled before the callback listener is removed).

The callback is scheduled on the `CoroutineDispatcher` as an `Executor` (for JVM platform) with `context[CoroutineDispatcher]?.asExecutor()` before launching the coroutine the callback is eventually called in once the callback reaches my own code. Since a child coroutine isn't actually launched until the callback in the future, `TestScope.advanceUntilIdle` isn't able to advance to the needed time.

I looked into the idea of using something like `advanceUntilIdle()`, `advanceUntilBusy()`, and `advanceUntilIdle()`, to account for the suspend awaiting callback. I implemented `advanceUntilBusy`, based on `advanceUntilIdle`, as:

```
fun TestScope.advanceUntilBusy() = testScheduler.advanceUntilBusy()

fun TestCoroutineScheduler.advanceUntilBusy() = advanceUntilBusyOr { false }

internal fun TestCoroutineScheduler.advanceUntilBusyOr(condition: () -> Boolean) {
    while (true) {
        @Suppress("INVISIBLE_MEMBER")
        if (tryRunNextTaskUnless(condition))
            return
    }
}
```

and this actually mostly works, except for [this one test](https://github.com/cashapp/sqldelight/blob/master/extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt#L86-L97) only on the JVM platform. Apparently it's basic and quick enough that somehow it completes the callback within the first `advanceUntilIdle`, so `advanceUntilBusy` never completes and hangs. It's the one test that uses `withPagingDataDiffer` that wasn't failing on JVM before. The mechanism does work for all tests on native platforms.

So this solution seems to be more fragile even than an arbitrary `delay`, which I still don't like.

**Comment by dkhalanskyjb** [comment] 2023-07-26 17:58
Yes, this solution is worse than a `delay`: it doesn't get rid of a race (as shown by that one test that hangs with this approach), but also it contains a spin lock, wasting a lot of CPU time. The proper way to write tests is to either make them synchronous by having them run on a single thread, or to explicitly wait for the computations in whose results you are interested and continue with the checks only then.

**Comment by jeffdgr8** [comment] 2023-07-26 18:18
Yeah, I'll have to dig into the paging library's API some more and see if this test mechanism can be refactored somehow, to still test the first `load()` results without the arbitrary delay. I want to avoid building something into the code under test just to notify the test code.
