### ISSUE TITLE
Removed NoClassDefFound cycle until out of memory

### ISSUE THREAD

**Issue by nihiluis** [Kotlin/kotlinx.coroutines#488] opened 2018-08-12 16:28 UTC
```
2 Aug 18:18:13.36[kotlinx.coroutines.DefaultExecutor][^[[1;31mERROR^[[0;39m] java.lang.                NoClassDefFoundError: kotlinx/coroutines/experimental/internal/Removed
     at kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode.getPrev(LockFreeLinkedList.kt:   115)
     at kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode.addLast(LockFreeLinkedList.kt:   145)
     at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:121)
     at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:54)
     at java.lang.Thread.run(Thread.java:748)
 
 12 Aug 18:18:13.36[kotlinx.coroutines.DefaultExecutor][^[[1;31mERROR^[[0;39m] java.lang.                NoClassDefFoundError: kotlinx/coroutines/experimental/internal/Removed
     at kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode.getPrev(LockFreeLinkedList.kt:   115)
     at kotlinx.coroutines.experimental.internal.LockFreeLinkedListNode.addLast(LockFreeLinkedList.kt:   145)
     at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:121)
     at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:54)
     at java.lang.Thread.run(Thread.java:748)
 
 12 Aug 18:18:13.78[kotlinx.coroutines.DefaultExecutor][^[[1;31mERROR^[[0;39m] java.lang.                OutOfMemoryError: unable to create new native thread
     at java.lang.Thread.start0(Native Method)
     at java.lang.Thread.start(Thread.java:717)
     at kotlinx.coroutines.experimental.DefaultExecutor.createThreadSync(DefaultExecutor.kt:92)
     at kotlinx.coroutines.experimental.DefaultExecutor.thread(DefaultExecutor.kt:85)
     at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:80)
     at java.lang.Thread.run(Thread.java:748)

```
where is this coming from? I got no idea

**Comment by qwwdfsad** [comment] 2018-08-13 07:35
Could you please provide self-contained reproducer with version and platform?

**Comment by nihiluis** [comment] 2018-08-14 10:30
I know i have kotlin dependencies which grab a bunch of shit inferior kotlin versions (not the one I intend to)..
I updated kotlin to newest version in response and can not reproduce it atm and i was unable to do so before as well, because the error occurred with the same dependencies I used for months for the first time and didnt appear afterwards.

its kinda weird that the error appears so often though, it will literally consume all the resources and quickly run out of memory.  i hope it wont appear again.

**Comment by qwwdfsad** [comment] 2018-08-14 11:13
`NCDFE` is probably because you have a very old version of `kolinx.coroutines` in the classpath

Usually, it's worth to inspect `mvn dependency:tree` or `gradle :dependencies` to bisect where all these dependencies come from and exclude them.

>it will literally consume all the resources and quickly run out of memory.

Sure, application code is usually not ready to `NoClassDefFoundError` in a random code :)

I will close the issue as it's not a problem in `kotlinx.coroutines` itself

**Closed by qwwdfsad** 2018-08-14 11:13 UTC
Labels: waiting for clarification
